### ISSUE TITLE
Does not work without ssh keys

### ISSUE THREAD

**Issue by svenk** [tmate-io/tmate#100]
I tried this fantastic software with a remote linux novice which did not have any SSH keys installed on his system. I would strongly vote for having (at least for command line flag) an easy option to just go and generate a standard pair of ssh keys, without passphrase. Or to make tmate work also without any keys.

**Comment by nviennot** [comment]
oh so maybe a "no keys found, generate keys [y/n]?" prompt would be good?

**Comment by svenk** [comment]
Yes. It's just a call to `ssh-keygen`.

**Comment by lnxbil** [comment]
Thank you for the tip. This was exactly the piece of information missing to get it to work with Putty/Kitty.

For all future travellers. If you got the message in PuTTY/KiTTY:

```
Disconnected: No supported authentication methods available
(server sent: publickey)
```

Simple generate a new key with the `puttygen.exe` and attach this key to the `Default Settings` inside of PuTTY/KiTTY. Afterwards you can connect through the commandline by just replacing `ssh` with `putty` or `kitty` from the output of `tmate` itself

**Comment by michaeladamkatz** [comment]
When Inxbill says "attach this key to the Default Settings inside of PuTTY/KiTTY", that means in the KiTTY Configuration window, go to Connection > SSH > Auth and upload your .ppk file (generated with puttygen.exe or some other method) to the field "Private key file for authentication".
