### ISSUE TITLE
[Feature request] Allow supplying SSH connect options

### ISSUE THREAD

**Issue by ddjm1973** [tmate-io/tmate#102]
Right now "tmate" will try to directly connect to "ssh.tmate.io" on port 22 ... but what if I am behind a NAT firewall + lots of Proxy servers that don't allow direct SSH connections out?

"tmate" seems to ignore ~/.ssh/config ... so adding a section for "Host *.tmate.io" and adding an appropriate "ProxyCommand" (e.g. something like "ProxyCommand nc -X connect -x corporate.proxy.server:8080 %h %p"  ...) in there did not work for me.

But it would be nice if we could either configure this via ~/.ssh/config or even supply this directly to "tmate"? e.g. invoke "tmate" with a command like:

tmate -o "ProxyCommand=nc -X connect -x proxy.server.corp.net:8080 %h %p" -S /tmp/tmate.sock new-session -d

Cheers ;-)

**Comment by nviennot** [comment]
It would be indeed nice. Since we are using libssh at the moment, it's up to libssh to do all the magic.

**Comment by fhwedel-hoe** [comment]
tmate can be configured via `~/.tmate.conf`. I chose to set-up a tunnel to "ssh.tmate.io" manually and then use `tmate-server-host "localhost"` to make tmate connect through the tunnel.

**Comment by MaxGyver83** [comment]
@fhwedel-hoe: Could you explain how you created a tunnel?

**Comment by fhwedel-hoe** [comment]
`~/.tmate.conf` contents:

    set -g tmate-server-host "localhost"
    set -g tmate-server-port 4242

Before running `tmate`, open another shell and create the tunnel:

    ssh -L 4242:ssh.tmate.io:22 user@trustedserver.com

Where `trustedserver.com` is a server that allows port-forwarding and happens to be white-listed by the firewall I am sitting behind.

Then execute `tmate`.

**Comment by MaxGyver83** [comment]
Thanks for your answer! I'll have to check if there is a trusted server I can use for this.

**Comment by kcubeterm** [comment]
@fhwedel-hoe could serveo be the trusted port forwarder, if yes, then unfortunately your above example doesn't work for me
