### ISSUE TITLE
Broken emoji support (2.2.1)

### ISSUE THREAD

**Issue by sukima** [tmate-io/tmate#104]
In tmate 2.2.1 `cat` [this file (gist)](https://gist.github.com/96c4865e5e9b25af8179b4dc6494407e) and you'll see some emojis are missing.

Tried to capture this at https://asciinema.org/a/81pa326izm7zcfoh8trl0ihtr (their web support for emojis is not perfect).

| Name   | Version                            |
|--------|------------------------------------|
| Mac OS | `10.11.6` (`15G1217`) (El Capitan) |
| iTerm  | `3.0.13`                           |
| tmate  | `2.2.1` (via Homebrew)             |
| tmux   | `2.3` (via Homebrew)               |

**Comment by nviennot** [comment]
This will get resolved by changing the rendering engine to mosh.
