### ISSUE TITLE
mobile experience

### ISSUE THREAD

**Issue by derkens** [tmate-io/tmate#105]
I have set up tmate so that a user can push a button (in openhab) and pushover will send me the details.

first I've tried with changing the details to have ssl:// in front of it. This will, by clicking the url, open juicessh on my android phone and set up the connection. this however fails because of the way juicessh is handling ssh keys, they are couppled to an identity with a mandatory username. So a correct key is not used and not choosable. I think this is more an issue with juicessh than with tmate... A workaround may be a private tmate server with a fixed identity?

So I have changed the pushover link to the weblink tmate generates. This works well and chrome on my phone opens the link and logs in. It wont however open the soft keyboard on my phone. I guess this is because chrome does not see the session as an input area?
Is this something that can be helped or changed?

**Comment by nviennot** [comment]
hmm yes, this is a problem. However, I have no bandwidth at the moment to deal with it :/

**Comment by derkens** [comment]
Ok, I understand, thanks for the response.

**Comment by nviennot** [comment]
When using juicessh, one must create a new identity with the session key as user name, and a random generated key pair. Not the most fluid experience, I'll revisit the usage with JuiceSSH at a later point in time.
