### ISSUE TITLE
tmate fails to load public key containg a comment

### ISSUE THREAD

**Issue by mcstafford-git** [tmate-io/tmate#106]
When the comment is removed from the pubkey the server loads, prompting me to enter the private key's password.

* 4096-bit RSA ssh key.
* tmate 2.2.1-0~3~ubuntu16.10.1
* Ubuntu 16.10/yakkety

Logs from tmate -vvv attached, including success and failure.

[tmate-logs.zip](https://github.com/tmate-io/tmate/files/848877/tmate-logs.zip)

**Comment by nviennot** [comment]
I'm seeing things like

```
1489693988.741224 [tmate] D [1] [ssh_userauth_publickey_auto] ssh_userauth_publickey_auto: Failed to read private key: /home/USERNAME/.ssh/id_rsa
1489693988.741232 [tmate] D [3] [ssh_userauth_publickey_auto] ssh_userauth_publickey_auto: Trying to authenticate with /home/USERNAME/.ssh/id_dsa
1489693988.741243 [tmate] D [3] [ssh_userauth_publickey_auto] ssh_userauth_publickey_auto: Private key /home/USERNAME/.ssh/id_dsa doesn't exist.
```

It seems to have problems reading the key for some reason.
The issue stems from libssh. Perhaps a bug report at libssh would help.

**Comment by mcstafford-git** [comment]
I did have several keys present, including id_dsa. I moved it to ~/.ssh/disabled/ and am no longer able to reproduce the problem.

Thank you for tmate, and your time here.
