### ISSUE TITLE
Can't load SSH key (without passphrase)

### ISSUE THREAD

**Issue by philoozushi** [tmate-io/tmate#112]
Hi,

Thanks for this great job and service! :)

I had some problems connecting though.
It looks like tmate tries to use my default SSH key (which has no passphrase) during connection, but it always prompts a passphrase and doesn't seem to accept empty passphrases.

```
SSH key passphrase:
[tmate] Connecting to ssh.tmate.io...
[tmate] Can't load SSH key. Try typing passphrase again in case of typo. ctrl-c to abort.
[tmate] Can't load SSH key. Try typing passphrase again in case of typo. ctrl-c to abort.
[tmate] Can't load SSH key. Try typing passphrase again in case of typo. ctrl-c to abort.
```

My workaround :
I generated a new SSH key with a passphrase, renamed it to have it considered as default, and it worked. (although inconvenient).

Wouldn't empty-passphrase support be nice?
Or do you have any tips?

Thanks anyway.

**Comment by nviennot** [comment]
It would be, I'm not sure how to fix that
