### ISSUE TITLE
I upgrade the tmate to 2.2.1 and it doesn't work.

### ISSUE THREAD

**Issue by calee88** [tmate-io/tmate#113]
I am using Ubuntu 16.0.4.

When I used tmate from the default repository, it worked fine.

But, when I upgraded tmate to the version 2.2.1 following the instruction on the homepage, it doesn't work.

It just acts like tmux and doesn't show a token to ssh.

What did I do wrong?

**Comment by hirishh** [comment]
same here

**Comment by azamat-sharapov** [comment]
Same. I upgraded from apt repo on ubuntu and it stopped working (stuck in Connecting.... but never initiates connection). However, using "standalone" version worked well (tmate-2.2.1-static-linux-amd64.tar.gz).

**Comment by dexter816** [comment]
I confirm too!

**Comment by nviennot** [comment]
I suspect this is fixed
