### ISSUE TITLE
How can a script tell if it's in tmate?

### ISSUE THREAD

**Issue by benyanke** [tmate-io/tmate#114]
On my PS1, I specify information about my current terminal to keep up my awareness of where I am.

For example, a normal terminal:
![image](https://user-images.githubusercontent.com/4274911/29319079-46c74cc0-8198-11e7-9e91-15dc95a31639.png)

Or one within `screen`:
![image](https://user-images.githubusercontent.com/4274911/29319118-737c0b84-8198-11e7-9c0a-70fe2e985c26.png)

These can be accomplished by checking given env vars ($STY for screen, and $TMUX for tmux). Is there currently a setting, or could there be one specifying a few pieces of information? For example:

* Currently in a tmate session
* Current tmate session remote hostname

If they're not yet implemented, I might propose $TMATE and $TMATE_HOSTNAME

**Comment by nviennot** [comment]
You can check if you are in tmate by reading `$TMUX`. If it contains the string `tmate`, you are in tmate.

to display the session remote hostname, just run `tmate display -p '#{tmate_ssh}'`
