### ISSUE TITLE
Allow ssh connection based on .ssh/authorized_keys

### ISSUE THREAD

**Issue by slashmili** [tmate-io/tmate#118]
Hi

Thanks for the great software!

I'm just wondering if it's possible to add a flag or something that tmate only allow ssh clients with valid key connect to the tmate session.

Have thought about it? Do you think it would be something that you add someday to tmate?
And wondering if you can point me to the right direction, then I can take a look 😬

**Comment by nviennot** [comment]
Yes!

Follow my comment on https://github.com/tmate-io/tmate-slave/issues/37#issuecomment-332995619
