### ISSUE TITLE
Is possible running tmate inside of a tmux session?

### ISSUE THREAD

**Issue by ryukinix** [tmate-io/tmate#119]
Is common for me always starting tmux automatically with any terminal on my system. But if I try running `tmate` inside of `tmux` session I got:

```
❯ tmate
sessions should be nested with care, unset $TMUX to force
```

And attaching directly from the tmux server with `tmate attach` seems don't work. For now only works for me opening a new terminal without tmux running and run `tmate`.

I'm wondering if there is something better to do...

I appreciate the effort to do this is awesome and very useful service for the community.

**Comment by pinktrink** [comment]
I'm a month late to the party but you can run `TMUX=` in your terminal to unset it. This isn't necessarily a good idea though. Even the annoyance of having to send my prefix twice just to issue a command to my nested tmux isn't appealing.

**Comment by ryukinix** [comment]
> I'm a month late to the party but you can run TMUX= in your terminal to unset it. This isn't necessarily a good idea though. Even the annoyance of having to send my prefix twice just to issue a command to my nested tmux isn't appealing.

Yes, this is not cool. I solved it in another way. As I always use tmux on startup of my shell through as `zprezto` plugin, I wrote a little hack as tmate alias to load together:

```
alias tmate="tmux detach-client -E 'tmate;tmux'"
```

This execute tmate on the same window and plug again tmux client session on the end. It's dirty but works as expected.

[![works badge](https://cdn.rawgit.com/nikku/works-on-my-machine/v0.2.0/badge.svg)](https://github.com/nikku/works-on-my-machine)
