### ISSUE TITLE
libevent-2.0-5 (>= 2.0.10-stable) it's not installable on Ubuntu 17.10

### ISSUE THREAD

**Issue by deniscostadsc** [tmate-io/tmate#120]
Hi all,

I tried to install Tmate on Ubuntu, using the steps described on the Tmate page and reproduced below:

```
sudo apt-get install software-properties-common && \
sudo add-apt-repository ppa:tmate.io/archive    && \
sudo apt-get update                             && \
sudo apt-get install tmate
```

I got the following result:

```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://dl.google.com/linux/chrome/deb stable InRelease' doesn't support architecture 'i386'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 tmate : Depends: libevent-2.0-5 (>= 2.0.10-stable) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I already had a newer version of libevent installed on my machine because of Tor, but that didn't help:

```
$ dpkg -l | grep libevent
ii  libevent-2.1-6:amd64                  2.1.8-stable-4                           amd64        Asynchronous event notification library
```
I have installed libevent version 2.0.22-stable, [located here](https://github.com/libevent/libevent/releases/tag/release-2.0.22-stable), from the source following [these steps](https://github.com/libevent/libevent#0-building-and-installation-briefly). Since it was going to be installed in a different folder, I thought both versions could co-exist. But I got the same result when tried to install Tmate again.
 
It seems [I'm not the only person](https://askubuntu.com/questions/968022/install-tmate-ubuntu-17-10) having this problem.

I tried to reach [Javier López](https://github.com/chilicuil), to ask him about this. But the Github profile listed on the Tmate page gives me a 404 answer.

My machine info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

:heart:

**Comment by varac** [comment]
@deniscostadsc I use `tmate 2.2.1-1build1` that's included in the official Ubuntu 17.10 `universe` debian repo. Works fine for me.
The installation from the tmate repository should get fixed nonetheless.

**Comment by deniscostadsc** [comment]
I removed the repositories from source.list.d and it worked! Thanx @varac! But I think the issue still valid, because the package is not installable.

**Comment by foxx** [comment]
Same problem here, if it doesn't work then it should be removed.

**Comment by nviennot** [comment]
I removed the ppa from the install instructions
