### ISSUE TITLE
Cannot share files via scp

### ISSUE THREAD

**Issue by juusechec** [tmate-io/tmate#121]
I'm try something like this:
```bash
scp myFile BB9hJdBrTarZwZQ8zy4Z9WaERf@to2.tmate.io:/home/jorge
# Connection to to2.tmate.io closed by remote host.
# Invalid command
# ------- or with sftp ------- #
sftp BB9hJdBrTarZwZQ8zy4Z9WaERf@to2.tmate.io
# Connection to to2.tmate.io closed by remote host.
# Connection closed
```
But isn't working... Why?

**Comment by cjeanner** [comment]
hmm, not really sure this is an intended use of tmate. The server will not be able to forward files to the destination - it only has a tmux (tmate) instance running and both ends are attached to it.

tmate isn't an SSH proxy or this kind of thing.

**Comment by HaoZeke** [comment]
You probably want to combine your tmate sessions with [transfer.sh](https://transfer.sh/) or some such for transferring files.

**Comment by nviennot** [comment]
You can use [Magic-Wormhole](https://magic-wormhole.readthedocs.io/en/latest/) for this usecase

**Comment by NightMachinary** [comment]
@nviennot I get this error even on normal SSH:
```
❯ ssh x@lon1.tmate.io                                                                
Invalid command
Shared connection to lon1.tmate.io closed.
```
