### ISSUE TITLE
Cannot create socket with a remote server with tmate daemon

### ISSUE THREAD

**Issue by juusechec** [tmate-io/tmate#123]
Hello, I'm try to do a dynamic socket to use a remote machine like proxy socket. I'm try with:
```bash
ssh -D 9999 BB9hJdBrTarZwZQ8zy4Z9WaERf@to2.tmate.io
```
And use localhost:9999 like a socks proxy.
Try too with a typical socket with:
```bash
ssh -L 9000:google.com:80 BB9hJdBrTarZwZQ8zy4Z9WaERf@to2.tmate.io
```
and use
```bash
curl -v localhost:9000
```
to test it.

Both is enter to command line, but sockets never happend and nothing is working. Why?

Thanks

**Comment by nviennot** [comment]
socket forwarding is not yet supported.
thank you :)
