### ISSUE TITLE
Cannot create new sessions on ssh.tmate.io

### ISSUE THREAD

**Issue by bogdanap** [tmate-io/tmate#125]
Hi!

Our debug jobs at [Travis CI](travis-ci.org) have been experiencing issues connecting to `ssh.tmate.io` for the past couple of hours, so new sessions cannot be created.  
This is reproducible both from local environments and public cloud providers. 

Log output:

```
1520413129.946897 client 0x7f911e02fa00, status interval 15
1520413130.974808 [tmate] D [1] [socket_callback_connected] socket_callback_connected: Socket connection callback: 1 (0)
1520413130.974949 [tmate] D [1] [ssh_client_connection_callback] ssh_client_connection_callback: SSH server banner: SSH-2.0-tmate
1520413130.974991 [tmate] D [1] [ssh_analyze_banner] ssh_analyze_banner: Analyzing banner: SSH-2.0-tmate
1520413131.093801 [tmate] D Establishing connection to 46.101.170.73
1520413131.093946 [tmate] D Connected to 46.101.170.73
1520413131.094085 [tmate] D [1] [ssh_agent_get_ident_count] ssh_agent_get_ident_count: Answer type: 12, expected answer: 12
1520413131.094247 [tmate] D [1] [ssh_userauth_request_service] ssh_userauth_request_service: Failed to request "ssh-userauth" service
1520413131.193029 [tmate] D Auth successful
1520413131.223481 [tmate] D Session opened, initalizing tmate
1520413131.258075 [tmate] D Ready
1520413134.369435 [tmate] D [1] [ssh_packet_process] ssh_packet_process: Couldn't do anything with packet type 80
1520413140.339461 [tmate] D [1] [ssh_socket_exception_callback] ssh_socket_exception_callback: Socket exception callback: 1 (0)
1520413140.339534 [tmate] D [1] [ssh_socket_exception_callback] ssh_socket_exception_callback: Socket error: disconnected
1520413140.339597 [tmate] D Error reading from channel: Socket error: disconnected
1520413140.339646 [tmate] D SSH client killed (46.101.170.73)
```

**Comment by lamuria** [comment]
same problem here

**Comment by fearenales** [comment]
same here

**Comment by davidfernandes1212** [comment]
same problem here

**Comment by pdbradley** [comment]
Yup, same here.  :(

**Comment by jbendes** [comment]
Same here as well. Getting the following error when I type `tmate`:
```
Wed Mar  7 10:04:43 2018 [tmate] Connecting to ssh.tmate.io...
Wed Mar  7 10:04:45 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:04:45 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:04:50 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:04:50 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:04:53 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:04:53 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:04:57 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:04:57 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:05:01 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:05:01 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:05:05 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:05:05 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:05:09 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:05:09 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:05:13 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:05:13 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
Wed Mar  7 10:05:17 2018 [tmate] Error reading from channel: Socket error: disconnected
Wed Mar  7 10:05:17 2018 [tmate] Reconnecting... (Error reading from channel: Socket error: disconnected)
```

**Comment by m0dd3r** [comment]
same here, though it just changed from socket error to simply printing "connecting to ssh.tmate.io" but nothing else. Guessing it's being worked on.

**Comment by jsbueno** [comment]
Yep . I even tried running a local servers as per the homepage on tmate.io - the server goes up, but connection is failing all the same.

**Comment by m0dd3r** [comment]
I did the same, after manually compiling msgpack and libssh I finally got
tmate-slave to build, but it failed to run. I'm back to seeing the socket
error again now trying to start a tmate session against the public server.

**Comment by nviennot** [comment]
it's back!

**Comment by benjumanji** [comment]
I still seem to have the same problem, am I doing something dumb? I am just invoking plain `tmate` and `:show-messages` yields the log posted in https://github.com/tmate-io/tmate/issues/125#issuecomment-371167910

```
❯ tmate -V
tmate 2.2.1
```

**Comment by lamuria** [comment]
Same problem since yesterday. Any update?

**Comment by azat** [comment]
Same error here, does anybody experiences this issue right now?

**Comment by paolomeraviglia** [comment]
issue still present

**Comment by MartinPernus** [comment]
Same problem here.

**Comment by UrsZaugg** [comment]
We have the same problem. Are there any news on this.

**Comment by DanielSeehausen** [comment]
@UrsZaugg would you mind showing how you removed the Frankfurt server?

**Comment by UrsZaugg** [comment]
I have made a config file .tmate.conf with the following content (Frankfurt is missing):
set -g tmate-server-host "sf2.tmate.io" # San Francisco
set -g tmate-server-host "sg2.tmate.io" # Singapur
set -g tmate-server-host "to2.tmate.io" # Toronto
set -g tmate-server-host "ny2.tmate.io" # New York
set -g tmate-server-host "ln2.tmate.io" # London
set -g tmate-server-host "am2.tmate.io" # Amsterdam
You could also change the order of the server.

**Comment by anjakefala** [comment]
Currently running into this!

**Comment by marakalastic** [comment]
> Currently running into this!

I'm running into this as well and I'm located in Vancouver too. Looks like it's a server-side issue for tmate.

**Comment by Diana0604** [comment]
Same here! Tmate was not working on our remote server. Tested in a few different machines. Everywhere I get these errors:

`Connecting to ssh.tmate.io...
Error reading from channel: Socket error: disconnected
Reconnecting... (Error reading from channel: Socket error: disconnected)
Error reading from channel: Socket error: disconnected
Reconnecting... (Error reading from channel: Socket error: disconnected)`

**Comment by nightscape** [comment]
Same here. I'm currently using [upterm](https://github.com/owenthereal/upterm) as workaround.

**Comment by nviennot** [comment]
The issue should be fixed

**Comment by anjakefala** [comment]
Currently, running into this again on the West Coast!

**Comment by nviennot** [comment]
I'll take a look before end of week

**Comment by anjakefala** [comment]
It seems to have self-resolved for me! Things are working again now.

Thanks @nviennot!

**Comment by eladts** [comment]
I'm running into this issue again. I'm located in the US. After several retries tmate manages to connect to sgp1.tmate.io instead of nyc1.tmate.org which it usually connects to.

**Comment by yifanjia** [comment]
Hi eladts,
Do you know a full list of tamte servers? I am having the same issue and even worse, I can't connect to sgp1.tmate.io though it worked for you. Thanks!
