### ISSUE TITLE
Can I use tmate ssh link to SFTP access using Filezilla?

### ISSUE THREAD

**Issue by gauditano** [tmate-io/tmate#127]
Hi, I woul'l like to know if is there a way to use tmate ssh to access my server in Filezilla SFTP.
When I try, it's given me the error:
> Disconnected: No supported authentication methods available (server sent: publickey)

It seams that Filezilla remove what cames before "@" from "XxXXXXxxXXXXxxxXXXXxxXxxXxX@Xxx.tmate.io" and leave just "Xxx.tmate.io" as Host.

How can I do that?

**Comment by jtheo** [comment]
Have you tried to move the xxxxXXXxxxx in the user's field?

**Comment by nviennot** [comment]
Tmate does not provide file transfer support.
