### ISSUE TITLE
Security when the server is compromised

### ISSUE THREAD

**Issue by bbc2** [tmate-io/tmate#129]
If tmate.io or my custom tmate server were compromised, it seems to me that the attacker could take control of machines connected to it.  For instance, when I launch tmate-slave, I can see the session keys of every session in the server logs, and use them to control the clients.

The website discusses security considerations of the protocol but doesn't seem to take the aspect I described into account.  Could this be clarified so that users are aware of what they are actually protected against?

**Comment by nathankallman** [comment]
There is this white paper: https://viennot.com/tmate.pdf
That references in section `3.6 Threat Model` this exact attack vector and how it could be mitigated.
However, I do not know if the current tmate servers implement the proposed solution (or another solution).

I would also be interested in the answer to this question.

**Comment by nviennot** [comment]
We'll have end-to-end encryption in tmate 3.0

**Comment by jimeh** [comment]
@nviennot Any chance you've got a rough elbow guess of a timeframe for tmate 3.0? :)

**Comment by glyph** [comment]
I'm a little confused by this PR.  It says "closed", but there's no associated PR.  The website doesn't say anything about e2ee. `brew install tmate; tmate -V` says `2.4.0`, but the tag for that here is dated 2019.

Does this feature exist in released versions of `tmate`?
