### ISSUE TITLE
Is the web client also open source and self-hostable?

### ISSUE THREAD

**Issue by mavidser** [tmate-io/tmate#132]

**Comment by ssbarnea** [comment]
Sadly not, I was looking for the same feature: ability to share a readonly colored terminal output with others, one that would persist for a number of days even after the sharing session would end. I am still looking for such a solution, let me know if you found a reliable one.

This would make a really need feature request for tmate :)

**Comment by rbuzatu90** [comment]
Also I'm looking for this :-)

**Comment by nviennot** [comment]
https://github.com/tmate-io/tmate-master and https://github.com/tmate-io/tmate-frontend

Sorry for the lack of documentation...

**Comment by WladyX** [comment]
Can you please do a small quick and dirty howto for the above 2?
Thank you!

**Comment by nviennot** [comment]
1) Install [minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/) and [tilt](https://tilt.dev)
3) Clone all the repos of tmate-io in the same folder
4) Go in the tmate-kube/dev folder
5) run `eval $(minikube docker-env)`
6) run `tilt up`
7) go in tmate-master folder, and run `mix ecto.migrate`. This should create the postgres database. If this doesn't work, try running the migration from the master k8s pod.

You should have the whole tmate backend running locally
