### ISSUE TITLE
tmate PPA does not support bionic

### ISSUE THREAD

**Issue by skorokithakis** [tmate-io/tmate#137]
Installing tmate fails on the latest Ubuntu LTS, bionic.

**Comment by alexforever86** [comment]
When trying to update from tmate ppa, its giving 404.

```
Err:17 http://ppa.launchpad.net/tmate.io/archive/ubuntu bionic Release         
  404  Not Found [IP: 91.189.95.83 80]
```

**Comment by alexforever86** [comment]
At the end, I installed tmate with just `sudo apt install tmate`.

**Comment by skorokithakis** [comment]
I'm assuming it now doesn't support Cosmic (18.10) either, which seems important.

**Comment by nerdoc** [comment]
Is there a reason why bionic is not supported? It's a LTS with 10á support.

**Comment by nviennot** [comment]
I've tried installing tmate on bionic, seems fine
