### ISSUE TITLE
tmate-slave connection closed

### ISSUE THREAD

**Issue by jakobfriis** [tmate-io/tmate#140]
Hosting a tmate-slave on ubuntu 18.04 LTS gives me problems.
The code is built from git, and the port is set to 5001.

tmate-slave -p 5001 -h jdata.dk
<5> (tmate) Accepting connections on :5001

running tmate on a raspberry pi 3

ssh -p5001 6gnJ3drdZamFHbm9gBOSQ3IRL@jdata.dk

<5> [init] (tmate) Bootstrapping ssh client ip=192.168.1.1
<5> [6gnJ3drdZamFHbm9gBOSQ3IRL] (tmate) Spawning slave server for tmate at 192.168.1.1 (AAAAB3NzaC1yc2EAAAADAQABAAABAQCnfHUjyz+I+9Sd9/sbE7QFsXb8HqSJO4t+L3o6HTa5ynPjqrTMPQtPYDobgRNRde4m8M/RfxfMJh8fiAWkRfP1ymVp+71NaDAO4OS/6yFEMYJwqP42uXyq516EyPPotU1nBck8Wg9iM9hYREr/hipg620PTHygVa5c/YQq8aHgubPrsCJiW7k14ZhNHQ39eF6gMnxqs9gl/x2Sn+2EXso3nCz64zZIZRWYI7KRVMbz+NfcXi5mdiUAYzlanqf/0CJEfdlU8JMwN+rmB7q9T6ZrSazeMMyc3uu5HCX7ljOB+AP514eaQ+VVtYSFGtp0TVd6TW+rFMcltjvs8heqU/7P)
<5> [6gnJ3drdZamFHbm9gBOSQ3IRL] (tmate) Daemon header: client version: 2.2.1, protocol version: 6

Gives the following logs, and the connection is lost after 5s

<5> [pL21lWETfEBd0AmgwXeECPUWz] (tmate) Spawning slave client for 95.216.172.86 (AAAAB3NzaC1yc2EAAAADAQABAAABAQDnQHiR+j5ERCoQWuMB2gWxnELSNPoV6me79HTj/PC5rzbtiWLx7gsBDVWcHQ6xHGj+iHVe1DKpR+Cwm5kM8sKXN76NXLKcEmiQEwJh4anb3BlLwiweDwRQ+F20a3SwfPtScwJSc1etdfs1s8k7hwYaVW8X0alaX5I3thSyTQNfPhhFDhVhuyXqHe/PhnQ0Qjgqpqge7xLuZTlJbpgrsZ63WhOa7nsjofdznd+6fnp9seFdmV4fVeyyHVaPdjGw8R4cxSRBil3lzQSdwdIyFRw0nbXAYmy+esSreg/g4AipMEUOwnNy+FLI3/2vifjh4EJp3XtlYKVR4tyiDZr+HaM7)
<5> [pL21lWETfEBd0AmgwXeECPUWz] (tmate) Client joined (cid=0)
<2> [pL21lWETfEBd0AmgwXeECPUWz] (tmate) fatal: Error writing to channel:
<5> [pL21lWETfEBd0AmgwXeECPUWz] (tmate) Client left (cid=0)

tmate is run using the follwing configuration
set -g tmate-server-host "jdata.dk"
set -g tmate-server-port 5001
set -g tmate-server-rsa-fingerprint   "..."
set -g tmate-server-ecdsa-fingerprint "..."

**Comment by alvgot** [comment]
Hi i have the same problem on devuan ascii:
<2> [h16vUbOCTSAqC20YJMfhlGNg6] (tmate) fatal: Error writing to channel: 
<5> [h16vUbOCTSAqC20YJMfhlGNg6] (tmate) Client left (cid=0)
<6> [h16vUbOCTSAqC20YJMfhlGNg6] (tmate) [ssh_packet_unimplemented] ssh_packet_unimplemented: Received SSH_MSG_UNIMPLEMENTED (sequence number 15)

**Comment by alvgot** [comment]
Everything seems to work fine but no with the sessions !!!
How can we solve this ???

**Comment by alvgot** [comment]
Hi jakobfriis, did you found how to solve this problem or you still having it ???
At the moment i didn't found any solutions !!!! 
Anyway keep in contact

**Comment by nviennot** [comment]
Use libssh 0.9.0 and you'll be okay
