### ISSUE TITLE
Can I detach and reconnect to tmate.io using some command or how?

### ISSUE THREAD

**Issue by r51303** [tmate-io/tmate#142]
Hello, 
my tmate version is latest : 2.2.1+201706011546+stable3~ubuntu16.04.1
I show that this version will allow reconnecting to tmate.io

And then I use the tmate -S option to attach my detached session,
but there is not reconnecting in process...

How could I do to use any command or options to reconnect to tmate.io?
Even if there is a new session to server, that's okay.

But, I really need to reattach my terminal then reconnect to tmate.io.

Help me, please.
Thank you.

**Comment by nviennot** [comment]
I don't understand the question. Can you rephrase please?
