### ISSUE TITLE
Invalid or expired session token

### ISSUE THREAD

**Issue by starplanet** [tmate-io/tmate#144]
tmate reconnect mechanism may have a problem. I found that if my machine which behinds a nat server change dynamic ip, the existing ssh connection will be expired. You should explicitly attach the tmate session on the machine to reactivate the connection to tmate slave server.

**Comment by kuien** [comment]
My case: Host A creates an session XX, and Host B attaches to remote session XX through ssh. But, Host A changes to another WIFI (there are 5+ different WIFI SSID in my office, grrrr), then Host B found his terminal is HANG without any response. Timeout or des-attach may be more friendly for users on Host B.

**Comment by sys49152** [comment]
Yes would be nice if the connection between the host running tmate server and tmate-slave server could be monitored. That could restart the tmate server to reestablish the connection between tmate server and tmate-slave server. Then at least I would be able to write a script to do so.

**Comment by nviennot** [comment]
the tmate client should reconnect automatically if the connection drops.

**Comment by sys49152** [comment]
Yes it should, but if not?
I need something to get the current state.
Well there is:
`tmate -S /tmp/tmate.sock wait tmate-ready`
I'd like to have something non blocking.

> the tmate client should reconnect automatically if the connection drops.
> […](#)
> On Sat, Oct 5, 2019 at 5:17 PM sys49152 ***@***.***> wrote: Yes would be nice if the connection between the host running tmate server and tmate-slave server could be monitored. That could restart the tmate server to reestablish the connection between tmate server and tmate-slave server. Then at least I would be able to write a script to do so.

**Comment by nviennot** [comment]
What's your usecase?

**Comment by nviennot** [comment]
* Are you using 2.3.0 on the client side?
* On the server side, are you using your own servers, or the tmate servers?
* If you are using tmate servers, what's your session token? I'll look up
the logs and see what's going on. Send it in private though, email is good.

**Comment by nviennot** [comment]
I have re-enabled keep alives. Dead connections should fall within 60 secs.

**Comment by janboeye** [comment]
I met same issue. 
Server log as follow:
[mEjS...] fatal: Expired token

Any solution for this issue?
Thanks
