### ISSUE TITLE
How can I start tmate in the background and with password passed from the command line?

### ISSUE THREAD

**Issue by bitcoinmeetups** [tmate-io/tmate#145]
How can I start tmate in the background and with password passed from the command line?

Hello,

So I would like to start tmate using something like tmate ssh-password un34jkn12jk3netc

Is it possible to do that?

I would also like to start tmate in the background so that I can stay in the same window and not get thrown into a new one every time I start tmate.

Is it possible to combine these two methods?

Mockup:

 tmate ssh-password un34jkn12jk3netc --background

**Comment by nviennot** [comment]
Starting tmate in the background is easy:

```
tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a headless mode
tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh_ro}' # Prints the read-only SSH connection string
tmate -S /tmp/tmate.sock display -p '#{tmate_web}'    # Prints the web connection string
tmate -S /tmp/tmate.sock display -p '#{tmate_web_ro}' # Prints the read-only web connection string
```

But you cannot pass the ssh password via command line, sorry
