### ISSUE TITLE
Outdated releases

### ISSUE THREAD

**Issue by paolomainardi** [tmate-io/tmate#153]
Hi everyone! It seems that last release has been published on 2016: https://github.com/tmate-io/tmate/releases/tag/2.2.1

We are facing some problems on having tmate client to support ed25519 keys, that are been merged into the master branch.

Are any new release already scheduled ? Are there any blockers that i can help to solve ?

**Comment by nviennot** [comment]
I'll take care of this next week

**Comment by paolomainardi** [comment]
Thanks a lot @nviennot, would be nice to map the tags with the the docker images as well, instead of having just :latest

**Comment by paolomainardi** [comment]
@nviennot do you have time to update the releases ?

**Comment by devn** [comment]
@nviennot Giving this a bump. Any chance you can find the time?

**Comment by nviennot** [comment]
I'm wrapping up another project, and I will be able to get back to tmate. Sorry for the delay.

**Comment by cryptomilk** [comment]
We need a release to work nicely with libssh 0.9.0.

**Comment by nviennot** [comment]
I agree. I will do it tonight. Thank you

**Comment by nviennot** [comment]
Done!
