### ISSUE TITLE
libssh 0.9.0 - "lost server"

### ISSUE THREAD

**Issue by jbrechtel** [tmate-io/tmate#154]
I don't know if this is an issue per-se but when tmate is built against libssh 0.9.0 then I get a "lost-server" immediately upon execution. I had to downgrade to libssh 0.8.7 to get it working again.

Just a heads up to anyone that might be experiencing this.

**Comment by Prior99** [comment]
I am experiencing the same issue.

**Comment by devn** [comment]
Thank you for posting this. We wound up figuring it out ourselves, but I hope this saves someone the hassle of tracking down what changed in their environment.

**Comment by Prior99** [comment]
Did you downgrade or how did you solve it?

**Comment by devn** [comment]
@Prior99 downgrade to 0.8.7

**Comment by eworm-de** [comment]
This starts to fail after libssh commit [channels: Add check if we are authenticated before we create a channel](https://git.libssh.org/projects/libssh.git/commit/?id=8a885f0bd38987ef135ff1638eeeb98a0a1edd70).

**Comment by cryptomilk** [comment]
Could someone please test #157 with libssh 0.9.0?

**Comment by spastorino** [comment]
I've just tested it and doesn't work. It doesn't fail with lost server anymore but keep trying to connect to ssh.tmate.io and giving cannot authenticate server.

**Comment by cryptomilk** [comment]
@spastorino Could you run it with `tmate -vvvvv` to get logging from libssh?

**Comment by eworm-de** [comment]
Well, this works with my own server...
You are right that ssh.tmate.io fails. By any chance a server issue?

**Comment by cryptomilk** [comment]
It looks like the default values for the server fingerprints are returned.

**Comment by cryptomilk** [comment]
```
21161 1564489402.647877 [tmate] D exptected hash:·
21162 1564489402.647883 [tmate] D server    hash: SHA256:8GmKHYHEJ6n0TEdciHeEGkKOigQfCFuBULdt6vZIhDc
```

expected hash should be the one returned from `options_get_string(..., tmate-server-ecdsa-fingerprint)` and that seems to fail and return just `\0`

**Comment by cryptomilk** [comment]
I think I know what's wrong, it doesn't know RSA-SHA2.

**Comment by cryptomilk** [comment]
I've fixed the next issue, but now it fails with rekeying issues.

**Comment by cryptomilk** [comment]
#157 has two patches now. However there seems to be a rekeying issue now.

**Comment by cryptomilk** [comment]
#157 works for me.

**Comment by eworm-de** [comment]
Same for me, looks good on ssh.tmate.io and my own server.

**Comment by M0ses** [comment]
after building the newest version, I got into a loop with the following message:

```
Reconnecting... (Cannot authenticate server)
```

**Comment by spastorino** [comment]
@cryptomilk yeah, now works perfect and it the fix was included in the ArchLinux package.

**Comment by eileencodes** [comment]
I'm experiencing the `Reconnecting... (Cannot authenticate server)` after upgrading to the latest verison. I'm using Sierra 10.12.6. I'm attaching the client log. Let me know if you need anything else.

[tmate-client-8395.log](https://github.com/tmate-io/tmate/files/3522483/tmate-client-8395.log)

**Comment by nviennot** [comment]
I'm in the process of upgrading the servers, it's going to get better
