### ISSUE TITLE
Error reading from channel: Socket error: disconnected

### ISSUE THREAD

**Issue by paolomainardi** [tmate-io/tmate#155]
It happens a lot in the last few weeks, making the service unusable, i know that everything is offered for free and that the server part can be deployed anywhere, just to understand if we can expect to use again tmate.io in a reliable way,

**Comment by WitekL** [comment]
Bumping this issue. Maybe there is some way we can help with enhancing the infrastructure side of this project? Maybe some crowdfunding or anything to keep it stable and reliable? Because I've been using tmate a lot and I love it!

**Comment by nviennot** [comment]
Damn, I'm sorry. Right now I'm back in putting efforts on tmate. Thank you for offering help. I need some.

Also "Socket error: disconnected" should not be fatal. tmate should reconnect, and everything should resume just fine, with the exception that SSH client must reconnect.

I'm migrating the infrastructure to kubernetes. For this, I need to upgrade the Elixir code to newer version. The proxy is done, I now need to finish the master. It shouldn't take much longer to get the infrastructure back to a good place.

I could use some help to setup automatic static builds of tmate (linux-x86, linux-amd64, darwin-adm64, linux-arm64, linux-armel). To then be uploaded to https://github.com/tmate-io/tmate/releases

**Comment by nviennot** [comment]
I've completed the migration to kubernetes, and the static builds are ready :)

Let me know if the issues are still present. Thank you for your patience.
