### ISSUE TITLE
Reconnecting... (Cannot authenticate server)

### ISSUE THREAD

**Issue by M0ses** [tmate-io/tmate#158]
After building the latest master (with #157) I got in a loop with the following error message:
 
```  Reconnecting... (Cannot authenticate server)```

**Comment by M0ses** [comment]
I forgot to mention that this was on my private instance - using tmate.io I get

Reconnecting... (Error reading from channel: Socket error: disconnected)

**Comment by M0ses** [comment]
@cryptomilk : my packages can be found here:

https://build.opensuse.org/package/show/home:M0ses:tmate/tmate

**Comment by eworm-de** [comment]
With what version of libssh?

**Comment by M0ses** [comment]
The package is 

libssh-devel-0.9.0-1.1.x86_64

included in the current version of openSUSE Tumbleweed.

**Comment by cryptomilk** [comment]
The current master works for me. If you have your own instance, did you update the fingerprints? They should be SHA256 ...

**Comment by M0ses** [comment]
@cryptomilk I see - now it works fine. Sorry for the noise
