### ISSUE TITLE
2.3.0 release doesn't have any binary asset

### ISSUE THREAD

**Issue by BanzaiMan** [tmate-io/tmate#159]
https://github.com/tmate-io/tmate/releases/tag/2.3.0 only has tarballs.

**Comment by nviennot** [comment]
I'd like to have the static build automatically created. Can someone help?
(Linux i386+amd64+arm64+armv7, and Darwin)

**Comment by BanzaiMan** [comment]
How is it built? If Travis CI can build it, it might be straightforward to incorporate it with https://docs.travis-ci.com/user/deployment/releases

**Comment by BanzaiMan** [comment]
ARM is not possible on Travis CI, but maybe crosscompilers would help. (I'm not experienced in this area.)

**Comment by nviennot** [comment]
I used to use the following: https://github.com/tmate-io/tmate/blob/master/Makefile.static-build

But it's a bit outdated. I'd be very happy if someone sets up the Travis builds.

I'm currently working on migrating the infrastructure to kubernetes

**Comment by michal-at-travisci** [comment]
Hi @nviennot 

Re:

> ARM is not possible on Travis CI (...)

Travis CI can currently support amd64 and arm64 (v8) builds - see [Multi-CPU architecture support for your builds](https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support).

Is your https://github.com/tmate-io/tmate/blob/master/Makefile.static-build still valid?

Also, I believe #165 is related

**Comment by nviennot** [comment]
I see, then we should be able to do it with Travis.
The makefile.static is still valid, except the versions numbers for the
libraries in it are outdated

**Comment by nviennot** [comment]
The static binaries are now built in a docker container running on travis-CI. The binaries are uploaded on the [github release page of tmate](https://github.com/tmate-io/tmate/releases). The binaries are available for a few platforms. Let me know if this works :)
