### ISSUE TITLE
x86_64 static build

### ISSUE THREAD

**Issue by alexander-bespalov** [tmate-io/tmate#160]
I'm getting the following issue while trying to make a static build for x86_64 platform. Appreciate any help on this.

```
# make -f Makefile.static-build
<SKIPPED>
/tmp/cc2Pc1nX.ltrans1.ltrans.o: In function `make_label':
/home/bespalov/tmate/tmux.c:155: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
libc/fdelt_chk.o: In function `__fdelt_chk':
(.text+0x16): undefined reference to `__chk_fail'
/usr/bin/ld: tmate: hidden symbol `__chk_fail' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:719: recipe for target 'tmate' failed
make: *** [tmate] Error 1
```

Thanks!

**Comment by nviennot** [comment]
The static binaries are now built in a docker container running on travis-CI. The binaries are uploaded on the [github release page of tmate](https://github.com/tmate-io/tmate/releases). The binaries are available for a few platforms. Let me know if this works :)
