### ISSUE TITLE
What's the right way to install tmate latest at ubuntu?

### ISSUE THREAD

**Issue by minhoryang** [tmate-io/tmate#163]
I couldn't get tmate latest from PPA (as tmate.io suggested).
And the github link of maintainer for Ubuntu packages are missing.

tmate 2.3.0 static binary also missing.
No CI running for static building.

What's the right way to install tmate latest at ubuntu?

**Comment by nviennot** [comment]
There's no right way, static builds are not made yet, I need some help doing that

**Comment by jungle-boogie** [comment]
Does it not build with the git master src?

**Comment by bartekbrak** [comment]
> Does it not build with the git master src?
It didn't for me on 18.04, I needed to install newer libss-4
```
$ apt show libssh-4 |& grep Version
Version: 0.8.0~20170825.94fa1e38-1ubuntu0.2
$ cat /etc/issue
Ubuntu 18.04.3 LTS \n \l
$ ./configure
...
configure: error: "libssh >= 0.8.4 not found"
```
followed instructions to get newer libssh at https://launchpad.net/~kedazo/+archive/ubuntu/libssh-0.7.x
and got it to compile from source with
```
$ apt show libssh-4 |& grep Version
Version: 0.9.0-0up3
```

Maybe this will help some one.

**Comment by nviennot** [comment]
I've added static binaries on the [release page](https://github.com/tmate-io/tmate/releases/). This should help

The ubuntu packages are not yet updated to the latest tmate version. The old tmate version has issues with newer version of libssh.
