### ISSUE TITLE
tmate 2.2.1 to private tmate-server 2.3.0 Cannot Authenticate

### ISSUE THREAD

**Issue by geofffranks** [tmate-io/tmate#164]
Having problems authenticating to a private tmate-server running on 2.2.1 after brew installing/upgrading to 2.3.0 on the client side. The errors we see client side are  Reconnecting... (Cannot authenticate server). Server-side, it shows connections dropping from the clients.

Is there anything we can do to reconfigure either the client or server to be compatible with each other? We're specifing rsa + ecdsa fingerprints in our tmate.conf files, using SHA256 syntax, and that isn't helping (have also tried MD5). Changing the version running on the server is going to be difficult for our situation, just looking for a way to get our newly installed laptops able to work with our existing tmate server.

Thanks

**Comment by nviennot** [comment]
Try the latest tmate-ssh-server and give it only RSA keys

**Comment by geofffranks** [comment]
Unfortunately we can't use the latest tmate-ssh-server. Running on xenial, with no msgpack 1.2.0 available, so can't compile ourselves, and no access to external PPAs to install packages from.

**Comment by nviennot** [comment]
You could build msgpack from source. But that's going to be a pain in the butt. You could also use the docker image tmate/tmate-ssh-server

**Comment by tdsparrow** [comment]
same problem here with tmate 2.2 connection latest tmate-ssh-server image, only RSA host key enabled.
Some server log:

Exchanging DH keys
[ssh_server_connection_callback] ssh_server_connection_callback: SSH client banner: SSH-2.0-libssh_0.7.0
[ssh_analyze_banner] ssh_analyze_banner: Analyzing banner: SSH-2.0-libssh_0.7.0
[ssh_kex_select_methods] ssh_kex_select_methods: Negotiated curve25519-sha256@libssh.org,ssh-rsa,aes256-ctr,aes256-ctr,hmac-sha2-256,hmac-sha2-256,zlib@openssh.com,zlib@openssh.com,,
[ssh_packet_server_curve25519_init] ssh_packet_server_curve25519_init: SSH_MSG_KEX_ECDH_REPLY sent
[ssh_init_rekey_state] ssh_init_rekey_state: Set rekey after 4294967296 blocks
[ssh_init_rekey_state] ssh_init_rekey_state: Set rekey after 4294967296 blocks
[ssh_packet_server_curve25519_init] ssh_packet_server_curve25519_init: SSH_MSG_NEWKEYS sent
[ssh_packet_newkeys] ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
[ssh_socket_exception_callback] ssh_socket_exception_callback: Socket exception callback: 1 (0)
[ssh_socket_exception_callback] ssh_socket_exception_callback: Socket error: disconnected
Error polling ssh socket: Socket err

Client logs:
1573794434.557083 [tmate] D [1] [ssh_client_connection_callback] ssh_client_connection_callback: SSH server banner: SSH-2.0-tmate
1573794434.557089 [tmate] D [1] [ssh_analyze_banner] ssh_analyze_banner: Analyzing banner: SSH-2.0-tmate
1573794434.557093 @0 active pane not changed
1573794434.562200 @0 active pane not changed
1573794434.582136 [tmate] D Establishing connection to x.x.x.x
1573794434.582158 [tmate] D Cannot authenticate server
1573794434.582168 [tmate] D SSH client killed (x.x.x.x)
1573794434.582196 [tmate] D Reconnecting... (Cannot authenticate server)

**Comment by Anantgaur** [comment]
@tdsparrow did you manage to fix the error somehow ?
