### ISSUE TITLE
only one server host key works

### ISSUE THREAD

**Issue by bjacke** [tmate-io/tmate#166]
when there are multiple server host keys like rsa and ed25519, then tmate clients will only be able to authenticate the ed25519 key. The tmate-server-rsa-fingerprint setting only on the client will result in a "[tmate] Reconnecting... (Cannot authenticate server)" error. As soon as you remove the ed25519 host keys on the server and restart it, the clients can authenticate with the rsa key also. Shouldn't all the host keys be ready to authenticate against for clients?

**Comment by nviennot** [comment]
Yes, I confirm, this is a bug

**Comment by nviennot** [comment]
This is not an easy one to fix, so I won't fix.

The benefit of being able to specify multiple keys for the tmate client is to have the ability to upgrade the server keys smoothly.
