### ISSUE TITLE
debs packaging

### ISSUE THREAD

**Issue by smaftoul** [tmate-io/tmate#17]
On tmate.io you provide a PPA for ubuntu packages.
Could you provide in this repo the debian folder, so we can build up to date debian packages, on launchpad or outside of launchpad

**Comment by chilicuil** [comment]
Hi,

Thanks for the great program, I've noticed that there is no tmate bzr repository in launchpad which means the packaging is uploaded manually after each release. I'm not sure if that the desired procedure, anyway I'd like to let you know than there exist a recipe feature who allows to do it automatically.

Procedure
-------------

Import the repositories to lp: https://code.launchpad.net/+code-imports/+new

https://github.com/nviennot/tmate.git
https://github.com/nviennot/tmate-ppa.git

Create a recipe on either https://code.launchpad.net/~your-user/+recipe/tmate or https://code.launchpad.net/~your-user/+recipe/tmate-ppa with the following content.

```
# bzr-builder format 0.3 deb-version {debversion}
lp:~your-user/your-project/tmate
nest-part deb lp:~your-user/your-project/tmate-ppa debian debian
```

Select the target ubuntu releases and save the preferences.

For future browsers, I created a recipe who builds continuously tmate using the above instructions, you may found it handy if you're interesed on installed the latest tmate code (which I assume is stable)

https://code.launchpad.net/~minos-archive/+recipe/tmate
https://code.launchpad.net/~minos-archive/+archive/ubuntu/main

**Comment by nviennot** [comment]
Thanks @chilicuil -- Yes I was doing things by hand. However, I was looking at https://github.com/jordansissel/fpm and it looks promising to do hassle-free packaging.
I'll look at both solutions when I'll have to deploy again :)
