### ISSUE TITLE
[NEW FEATURE] Add write permission to web session.

### ISSUE THREAD

**Issue by kcubeterm** [tmate-io/tmate#173]
The write permission to web session help to 
access terminal from anywhere like from smartphone etc

**Comment by nviennot** [comment]
It's already there, there's a write and read-only mode for the web session.
Maybe I don't understand what you mean

**Comment by kcubeterm** [comment]
But I did not find
Can you explain more about it

**Comment by kcubeterm** [comment]
Yes it's already there .
But it's not completely supported.
1.keyboard doesn't show everytime.

**Comment by nviennot** [comment]
Got it, I'll improve the terminal access soon.

**Comment by kcubeterm** [comment]
Very very thankful for improvement of web session

**Comment by nviennot** [comment]
I pushed new changes, I hope it's better :)
