### ISSUE TITLE
Exit session on disconnect

### ISSUE THREAD

**Issue by wr0ngway** [tmate-io/tmate#174]
I have a service which creates a tmate session on-demand, lets one connect to it, then on client exit, tears it all down. As such, I start tmate using the following so that my docker container exits when the last line exits:

```
tmate -S /tmp/tmate.sock new-session -d 
tmate -S /tmp/tmate.sock wait tmate-ready
tmate -S /tmp/tmate.sock display -p '##{tmate_ssh}'
tmate -S /tmp/tmate.sock wait session-exit
```

Is there a better way to do this, maybe a way to get the equivalent behavior when running with `tmate -F`?

**Comment by nviennot** [comment]
Use `tmate -F`, but in your tmate configuration file, `set tmate-foreground-restart 0`. This will prevent tmate to restart when the shell exits, and retain the behavior you want.

**Comment by wr0ngway** [comment]
Perfect, thanks!
