### ISSUE TITLE
Build Static Release for OSX 

### ISSUE THREAD

**Issue by bradparks** [tmate-io/tmate#176]
Hey... cool idea! I'd like to have a static OSX binary I can share with devs.

I tried to run `./build_static_release.sh` but wasnt sure what to supply for args.

Is there a better/easier way to do this?

**Comment by nviennot** [comment]
I need a way to create the binaries automatically

I can't verify that your binary is what it says it does, so I won't distribute it.

**Comment by bradparks** [comment]
Hi - thanks for getting back to me - Sorry if I was unclear - I didnt mean that I wanted to give you a binary of anything!

All I was hoping for was a way to create a static binary of tmate for osx, though I can't quite see how this is done?

I tried building it using homebrew and copying that build of tmate to another machine, but it was missing some dynamic libraries.

In short - is there a way to build a static binary of tmate for osx?

**Comment by nviennot** [comment]
Oh, I see. There should be a way.

See .travis.yml to see how the script to build the static binaries is invoked
