### ISSUE TITLE
Running non-interactive commands

### ISSUE THREAD

**Issue by gdhgdhgdh** [tmate-io/tmate#179]
Hullo :)

I use `tmate` to provide secure reverse-SSH facilities. I trigger `tmate` on a target device and pass the `ssh` string back through MQTT messages - it works really well thanks to your excellent work :)

I'd like to be able to use that `ssh` string to execute a pre-set command, just like I might do with regular ssh, but with tmate it's not working... e.g.

```
$ ssh CxxxxxxxxxxxxxxxxxxxKL@lon1.tmate.io date
Invalid command
```

How should I pass a single command to the waiting `tmate` session?

**Comment by gdhgdhgdh** [comment]
To follow up on this, I managed to get it running in a really hokey way. I get the target device to launch this script with the extra commands I want to run. e.g. if I want to install a new version of a package, I `start-tmate.sh "apt-get update ; apt-get install -y my-package-name=1.0.0 ; sleep 5"`

`start-tmate.sh`
```
#!/bin/bash

MYRAND=$RANDOM

killall -q tmate || true
tmate -S /tmp/tmate.${MYRAND} new-session -d "$@"          # Launch tmate in a headless mode
tmate -S /tmp/tmate.${MYRAND} wait tmate-ready             # Blocks until the SSH connection is established
tmate -S /tmp/tmate.${MYRAND} display -p '#{tmate_ssh}'    # Prints the SSH connection string
```

Hope that helps someone later - it's super hokey because the output response will contain the `tmate` control / cursor movement ANSI sequences - not much I can do about that.

**Comment by doronbehar** [comment]
@gdhgdhgdh I hope you won't mind me resurrecting a 3 year old issue. It seems to me that this script helps you run non interactive commands from the tmate running machine, not from the `ssh` client. Please correct me if I'm wrong. If not, please reopen the issue 🙏.

**Comment by gdhgdhgdh** [comment]
Hello @doronbehar wow that's quite a blast from the past, I can barely remember what the use-case for this was. From glancing back at this, I wasn't able to get it running from `ssh` natively, but by passing the commands I wanted to run as args to the `tmate -d new-session` command. Clumsy, but it worked.

So yes you're perfectly correct that it's using the `tmate` client here rather than a native `ssh` client - either way it was on the client machine, and that satisfied my requirement at that time. :)
