### ISSUE TITLE
Compile error on Cygwin

### ISSUE THREAD

**Issue by bcbcarl** [tmate-io/tmate#18]
```
tmate-debug.c:1:22: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h>
                      ^
compilation terminated.
Makefile:839: recipe for target 'tmate-debug.o' failed
make: *** [tmate-debug.o] Error 1
```

**Comment by m42e** [comment]
Any progress on this issue

**Comment by dragon788** [comment]
I'd definitely love to have this working under Cygwin/Babun, as I use tmux there quite often.

**Comment by nviennot** [comment]
If someone figures it out, that'd be great!

**Comment by dragon788** [comment]
It just occurred to me that under Cygwin/Babun there is a cygpath executable that in some cases handles translating paths from Windows C:\stuff\more to more Unix-y /c/stuff/more style paths. I've run into a few tools that don't take kindly to this, or do their own pathing logic and freak out when they see under Cygwin's skirt and get a path style they weren't expecting. I wonder if that's what is happening to the descriptors.

**Comment by cultavix** [comment]
I've just tried to build it on Babun/Cygwin and all seems well, it just complains about `msgpack` not being there.
