### ISSUE TITLE
Foreground mode is broken due to double setup of stdout

### ISSUE THREAD

**Issue by Ih0rko** [tmate-io/tmate#190]
Please add patch that allows stdout output in foreground mode: "tmate -F" and prevents tmate exit when trying to log to stdout.
[fix_foregroud.txt](https://github.com/tmate-io/tmate/files/4293513/fix_foregroud.txt)

**Comment by nviennot** [comment]
Interesting, How would `if (log_file == f)` happen?

**Comment by Ih0rko** [comment]
tmate_foreground == 1:

proc_start("client", ...) -> log_open_fp(stdout);
proc_start("server", ...) -> log_open_fp(stdout);

But I'll fire another bug with better solution.
