### ISSUE TITLE
New tmate session without attaching

### ISSUE THREAD

**Issue by iamvery** [tmate-io/tmate#21]
With vanilla tmux you can create a new session without immediately attaching by:

``` bash
$ tmux new-session -d
$ tmux ls
0: 1 windows (created Sat Nov 16 10:34:53 2013) [231x61] (attached)
$ tmux attach
# You're in :thumbups:
```

With tmate the session doesn't seem to be available:

``` bash
$ tmate new-session -d
$ tmate ls
failed to connect to server
$ tmate attach
no sessions
```

Is this by design? My use case is to script the tmate session before attaching. What do you think? Am I coming at this from the wrong direction?

**Comment by EnricoRiccardi** [comment]
I would benefit from multiple session with tmate
