### ISSUE TITLE
vim colors in tmate

### ISSUE THREAD

**Issue by giovannigiordano** [tmate-io/tmate#229]
When using vim in tmate it show strange colors (first image)

<img width="1158" alt="Screen Shot 2020-11-20 at 12 29 51" src="https://user-images.githubusercontent.com/15145952/99795719-8d0e1d80-2b2c-11eb-99a1-2b32ae579f8d.png">

while it should be like this (vim in tmux)
<img width="1142" alt="Screen Shot 2020-11-20 at 12 34 11" src="https://user-images.githubusercontent.com/15145952/99795827-b75fdb00-2b2c-11eb-96d6-def9f734c2c7.png">

In my tmate conf I am sourcing tmux.conf, so it should have the same configuration.

**Comment by kcubeterm** [comment]
Check your TERM environment, set.your TERM environment as you like. You can set default terminal via .tmate.conf or .tmux.conf

```
set -g default-terminal "screen-256color"
```

**Comment by giovannigiordano** [comment]
My `TERM` is `screen-256color` and I already have this config in my .tmux.conf, I have tried adding it to .tmate.conf, but it has no effect
