### ISSUE TITLE
tmux scroll not working, bug or intended?

### ISSUE THREAD

**Issue by cj** [tmate-io/tmate#23]
So doing `alt + u` and then `k` to scroll up doesn't work as someone viewing another persons session.  It gets to the top of what is currently visible then won't go any further.  Is this a bug or intended?

**Comment by ALEX5402** [comment]
> The issue was running tmate in a nested tmate session. Scrolling would operate on the outer session, not inner.

do you have any alternative idea how we scroll inside a tmate session
