### ISSUE TITLE
Error reading from channel: Socket error: disconnected

### ISSUE THREAD

**Issue by marakalastic** [tmate-io/tmate#237]
Seems to only be affecting devices in Vancouver, BC. @anjakefala from this post [https://github.com/tmate-io/tmate/issues/125](url) started experiencing this same error at the same time as me and it seems she's located in Vancouver as well.

Also can't connect to existing devices in Vancouver that already had tmate installed and running. Devices in other areas (Calgary, for example) running tmate can be successfully connected to.

Thanks!

**Comment by nviennot** [comment]
I reprovisioned the san fransisco server. It should be better now

**Comment by anjakefala** [comment]
Thanks so much @nviennot! :blush:
