### ISSUE TITLE
SSH Agent forwarding?

### ISSUE THREAD

**Issue by jneeven** [tmate-io/tmate#244]
Hi! First of all, thanks for creating this tool. It's very useful for remotely getting things done on devices of non-technical people.

I'm running into the following problem:
On the host device, I need to download a private git repository, and therefore I need to use my personal SSH key. If I connect to any device without `tmate`, this can easily be achieved with `ssh -A name@ip`. However, with `tmate` this appears not to work; I don't get any errors but it simply seems to still not be using my SSH key (trying to access that git repo will return `permission denied`). 
Is SSH agent forwarding explicitly not supported, or am I just doing something wrong? I haven't been able to find any more information on this.

Thanks!

**Comment by nviennot** [comment]
Hello,

You are right, SSH agent forwarding is not supported at this time

Nico

**Comment by jneeven** [comment]
That's unfortunate... Thanks for the quick reply!
