### ISSUE TITLE
Add support for the XDG Base Directory Specification

### ISSUE THREAD

**Issue by delvatt** [tmate-io/tmate#265]
Hi everyone, 

I was just wondering if **tmate** ever considered supporting the [XDG base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), especially `XDG_CONFIG_HOME `for the default configuration file, otherwise fall back to `~./tmate.conf` for backward compatibility.

For example, **tmux 3.1** introduced `~/.config/tmux/tmux.conf` and in [3.2](https://github.com/tmux/tmux/blob/a5f99e14c6f264e568b860692b89d11f5298a3f2/CHANGES#L145) `XDG_CONFIG_HOME/tmux/tmux.conf` was added.

**Comment by pierreprinetti** [comment]
in the meantime, you can put this into your `.{bash,zsh}rc` file:

```bash
alias tmate='tmate -f "${XDG_CONFIG_HOME}/tmate/tmate.conf"'
```

**Comment by delvatt** [comment]
@pierreprinetti  Fair enough! (I've definitely missed that -f flag). Thank you very much. 

Maybe one last thing would be to include these locations (`~/.config/tmux/tmux.conf` and `XDG_CONFIG_HOME/tmux/tmux.conf`) into the default lookup path, even if I'm not sure how much effort such a change might require and if it will be worth it.  What do you think ?

**Comment by delvatt** [comment]
At least, I consider the issue (uncluttered ~ ) resolve for me so again, thank you!
