### ISSUE TITLE
Partnering opportunity with `devsession.is`

### ISSUE THREAD

**Issue by RaafatTurki** [tmate-io/tmate#270]
I'm here serving as a "peace broker" to suggest a partnering opportunity with `https://devsession.is`.

The service was meant to be something similar to tmate.io that uses [zellij](https://github.com/zellij-org/zellij) as the backing technology but as I'm sure you know maintaining such infrastructure is no easy task.

I urge you to give zellij a try exploring its capabilities as it truly elevates the terminal multiplexing scene.

The lead developer behind that is [Aram Drevekenin](https://github.com/imsnif) a terrific guy and an awesome developer.
I've already talked with him on the matter and I quote
> ["I want to live in this world. If someone else takes up this project, I will help however I can."](https://www.reddit.com/r/commandline/comments/wb101x/comment/ii5a4cb/?utm_source=share&utm_medium=web2x&context=3)

I want to live in that world as well and I believe many others do too.

He's even willing to give away the `devsession.is` domain (allowing the cool `my.devsession.is/bobs-session` url scheme) if this becomes a serious matter.

I'm using the term "Partnering" loosely here as I'm not sure about what the business models for either sides are.
I'm certain this would make astonishing use cases possible like real pair programming over ssh, here are a couple previews with what that might look like (with default zero config zellij and no plugins)

*2 developers working on 2 different files in the same project (2nd developer is in the 2nd tab)*
![image](https://user-images.githubusercontent.com/16624558/181818568-a33c75a4-7ead-45ab-adcb-4b1a782922da.png)

*same but side by side*
![image](https://user-images.githubusercontent.com/16624558/181818178-003e99d4-226e-4cb5-94f4-def932c930de.png)

**Comment by nviennot** [comment]
Hi  Raafat,

> I urge you to give zellij a try exploring its capabilities as it truly elevates the terminal multiplexing scene.

Zellij looks amazing (and I love the Rust language). I hope it overtakes tmux quickly. I will be trying it out.

I could do a re-write of tmate one day, but it's not a priority at this point. I'm indulging on other projects.

And yes, maintaining infrastructure is hard :)

**Comment by heyakyra** [comment]
Just to save future searchers, you're looking for ziina/zmate

https://github.com/ziinaio/zmate/issues/18

but still needs a default server as described already above

https://github.com/devsession-org/devsession-org.github.io/issues/1
