### ISSUE TITLE
Build with the system libssh version.

### ISSUE THREAD

**Issue by gladiac** [tmate-io/tmate#28]
Please let tmate look for the system library of libssh and use it on Linux.

**Comment by lucaskanashiro** [comment]
Any update?

**Comment by nviennot** [comment]
not yet. Still not done with my phd :(

**Comment by nviennot** [comment]
tmate has been upgraded to latest version of tmux. It is now using system libraries.

Run brew install --HEAD tmate if you use homebrew. Install from sources (git HEAD) if not.

**Comment by lucaskanashiro** [comment]
Thanks @nviennot ! Will you make a new release with these modifications?

**Comment by nviennot** [comment]
Soon!
I want to implement reconnections and fix some other bugs before I make a full release.
Soon soon.
