### ISSUE TITLE
Cannot detach/reattach?

### ISSUE THREAD

**Issue by norswap** [tmate-io/tmate#31]
Is there a reason that after dettaching (e.g with `C-b d` d or `tmate detach`), I am not able to reattach? `tmate attach` and `tmate list-sessions` both say "failed to connect to server". However, the `tmate` process is still running.

**Comment by cheater** [comment]
@nviennot say, think 10 years is enough of a wait for `tmate attach`?

**Comment by h2oearth** [comment]
10 years already and still waiting
