### ISSUE TITLE
[NEW FEATURE] Is it possible to make port forward on client tmate ssh session?

### ISSUE THREAD

**Issue by fabceolin** [tmate-io/tmate#37]
I want to connect on remote ssh client that connected on my server. Example:
- On tmate terminal and web server (suppose that the tmate terminal server and tmate web server is in the same machine)

```
tmate
```
- On tmate client

```
ssh -g -R 2222:localhost:22 -p${PORT} ${RANDOM_CODE}@server.ip
```
- On the tmate server 

```
ssh -p 2222 localhost
```

On the actual tmate implementation, is not possible to make port forward. Is it easy to implement this?

Thanks

**Comment by interarticle** [comment]
For now I achieve port forwards with socat, which requires a public IP on your computer or an intermediate server to redirect the connection.

**Comment by pkoretic** [comment]
:+1:

**Comment by arinaruck** [comment]
Hi! Is the forwarding is supported now since the issue is closed?

**Comment by Zibri** [comment]
fortunately localhost.run exists! tmate is a mess and needs registration. localhot.run does not.

**Comment by alex-eri** [comment]
> fortunately localhost.run exists! tmate is a mess and needs registration. localhot.run does not.

but only for http

**Comment by NightMachinary** [comment]
Any updates?

**Comment by MiracleCherryPie** [comment]
no and tmate will never get port forwarding feature

**Comment by MiracleCherryPie** [comment]
even on 2022, I still can't connect to QEMU VNC console through tmate and ssh port forwarding

**Comment by Zibri** [comment]
Give this a try: https://wshell2.zibri.repl.co

**Comment by tahayk** [comment]
any updates ?
