### ISSUE TITLE
How to run tmate in read-only mode?

### ISSUE THREAD

**Issue by felippenardi** [tmate-io/tmate#39]
Hello,

I'm trying to create a new session in read-only mode but can't find any way to do so. :(

The site says `tmate show-messages`, and the `man` says to add `-r` flag. I can't figure out how to use either.

**Comment by arc113** [comment]
> When you run `tmate show-messages` within a tmate session, what do you get?
I get 
```
$ tmate show-messages
You must specify a socket name with -S. For example: 
  tmate -S /tmp/tmate.sock new-session -d
  tmate -S /tmp/tmate.sock wait tmate-ready

```
Please help. I'm unable to use read only mode
