### ISSUE TITLE
tmate running a daemon has no clients

### ISSUE THREAD

**Issue by interarticle** [tmate-io/tmate#49]
When running tmate as a daemon, tmux commands that check for the current connected client(s) fail with the message "No client available" or "No clients", including choose-window, command-prompt, display-message etc.

Start tmate with (from tmate.io)

```
tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a detached state
tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh_ro}' # Prints the read-only SSH connection string
```

Then connect to the tmate session.  Try a command, e.g. "^bw".  Error screen:
![error-screen](https://cloud.githubusercontent.com/assets/1386918/5781548/a959562e-9d81-11e4-9ad7-ed21ec119359.gif)

**Comment by nviennot** [comment]
This is not because of the daemon feature, it's that these features are not implemented.
Even if you run tmate the normal way, the choose-window, command-prompt, and display-message are executed in the context of the primary client, which is broken. They should be run in the context of the one who initiated the command. This shouldn't be too hard to fix.

**Comment by jlangr** [comment]
We would love to see a fix shortly. We started using tmate recently and found it effective (and built a crummy little Ruby script to initiate a detached tmate session and post the link to slack--https://github.com/outpace/slackmate).

thanks!

**Comment by nviennot** [comment]
I've looked into it a bit more, and it turns out that all the users connected to tmate through an ssh connection have no client. This would require significant work, and so I won't be able to do it just yet due to lack of time.

**Comment by lemonzi** [comment]
Hi there -- any news on this? I think I'll just run a nested tmux inside tmate then. The main issue is I can, for instance, create new panes remotely but I can't kill them afterwards.

**Comment by nviennot** [comment]
not yet, I have no available bandwidth these days :(

**Comment by lemonzi** [comment]
No worries! Running a nested tmux session as I mentioned (with a different prefix via .tmate.conf) works like a charm for my needs. Thanks for the good work :)

**Comment by nviennot** [comment]
This issue would disappear if tmate removed its dependency on tmux. Maybe I'll take that challenge for tmate 3.0
