### ISSUE TITLE
Fixing vim plugins to be more tmate friendly

### ISSUE THREAD

**Issue by notahat** [tmate-io/tmate#55]
Not a bug report, but just something you might be interested in.

I've submitted PRs to a couple of vim plugins to make them play nicely with tmate:

- https://github.com/christoomey/vim-tmux-navigator/pull/81
- https://github.com/benmills/vimux/pull/130

**Comment by thewatts** [comment]
Hey @notahat - legit!

Thanks for doing that!

Quick question for you - are you using the most recent version of tmux with tmate?
After making your suggested adjustments (adding those lines to my `.tmux.conf` and `.tmate.conf`) - I still have trouble switching back and forth between tmux panes.

**Comment by notahat** [comment]
I've got everything installed with homebrew on Yosemite.

    $ brew info tmux
    tmux: stable 2.0 (bottled), HEAD

    $ brew info tmate
    nviennot/tmate/tmate: stable 1.8.10 (bottled), HEAD

Can you tell if the `TMUX_COMMAND` environment variable is set correctly inside your tmux and tmate sessions? If that's correct, is the `g:tmux_navigator_command` variable being set inside vim?

**Comment by nviennot** [comment]
tmate has been upgraded to latest version of tmux.

Run brew install --HEAD tmate if you use homebrew. Install from sources (git HEAD) if not.

Let me know if that fixes the issue.
