### ISSUE TITLE
Does not play nicely with tpm (tmux plugin manager)

### ISSUE THREAD

**Issue by nightscape** [tmate-io/tmate#60]
Hi @nviennot,

I've had this problem where I couldn't connect to our own tmate server.
It turned out that the problem seems to be that tmate and tpm don't play nicely together.
To reproduce, you can follow the steps for tpm installation here: https://github.com/tmux-plugins/tpm#installation

This issue is not super important (I've just commented out the `run` line from tpm), but maybe it helps if someone runs into a similar issue.

**Comment by nviennot** [comment]
tmate have been upgraded to latest version of tmux.

Run `brew install --HEAD tmate` if you use homebrew. Install from sources HEAD if not.

Let me know if that fixes the issue.

**Comment by thomet** [comment]
Hi @nviennot I have similar problem, same steps to reproduce but for me, tmate stuck on loading.

I have installed tmate with `brew install --HEAD tmate` and follow https://github.com/tmux-plugins/tpm#installation to install tpm.

That's my config:
```
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmate/plugins/tpm/tpm'
```

When I now try to start tmate, it stuck and I need to hard kill it.

Any ideas?

**Comment by Dan1jel** [comment]
Same here, tmate sucks on loading and have to force quick Termux. Works well when I remove the line from .tmux.conf

**Comment by jaclu** [comment]
I think it is due to tpm doing parts of its stuff by running tmux commands in a sub-shell, same as a lot of plugins do, assuming that the environment they want to manipulate is called tmux. When it is not things do not happen as intended

**Comment by amsitlab** [comment]
> I think it is due to tpm doing parts of its stuff by running tmux commands in a sub-shell, same as a lot of plugins do, assuming that the environment they want to manipulate is called tmux. When it is not things do not happen as intended


 [here?](https://github.com/tmux-plugins/tpm/blob/b699a7e01c253ffb7818b02d62bce24190ec1019/tpm#L12)

**Comment by jaclu** [comment]
> > I think it is due to tpm doing parts of its stuff by running tmux commands in a sub-shell, same as a lot of plugins do, assuming that the environment they want to manipulate is called tmux. When it is not things do not happen as intended
> 
> [here?](https://github.com/tmux-plugins/tpm/blob/b699a7e01c253ffb7818b02d62bce24190ec1019/tpm#L12)

Well that's one, but there are in total 20 if I don't misremember, I forked tpm and created a workaround to handle various versions of tmux for testing, I haven't gotten around to test it on tmate yet
