### ISSUE TITLE
Memory leak on El Capitan (OSX)

### ISSUE THREAD

**Issue by lukemarsden** [tmate-io/tmate#61]
There's a rather unfortunate issue with the latest release of OSX and tmux documented here: https://github.com/tmux/tmux/issues/108

I'm pretty sure I just experienced the same issues with tmate. Any chance of porting the fixes in tmux HEAD into tmate? I use both tmux and tmate in my workflow.

Ideally I'd then be able to install the fixed version with `brew install --HEAD tmate`.

Thanks!

**Comment by nviennot** [comment]
I will address this soon

**Comment by lukemarsden** [comment]
Thanks!

**Comment by evo21** [comment]
big thanks

**Comment by nviennot** [comment]
I've upgraded the homebrew formula. you should be able to `brew install --HEAD tmate`. Now the tmate code is updated to the latest tmux code as well.

**Comment by lukemarsden** [comment]
Thanks @nviennot!
