### ISSUE TITLE
Bumping tmate to a more recent version of tmux

### ISSUE THREAD

**Issue by glestaris** [tmate-io/tmate#62]
Hello,

are there any plans for upgrading the tmux version to something more recent than 1.8? Tmux 2.1 came out recently. 

Some of the settings in my `~/.tmux.conf` do not work with older versions of tmux. Additionally, I sometimes get the error:

```
protocol version mismatch (client 8, server 7)
```

This is probably caused because in tmux 1.9 the tmux protocol version got bumped.

Thanks.

**Comment by sukima** [comment]
Yes!! How do we +1 this? Concerned that project might have atrophied.

**Comment by nviennot** [comment]
I'm working on it. Should be done by end of week

**Comment by sukima** [comment]
@nviennot Impressed. You are awesome! :panda_face:

**Comment by glestaris** [comment]
Thanks a lot @nviennot!

**Comment by nviennot** [comment]
Okay, so I've updated the server side, with an HTML5 client (the URL shows up after 10 seconds when using tmate).

Now I can update the clients :)

**Comment by nviennot** [comment]
I've updated the code of tmate-slave and tmate on master to the new tmux code.
It was a fair amount of work actually. Lots of things have happened in tmux during the past 3 years!

**Comment by glestaris** [comment]
Thank you very much @nviennot.
