### ISSUE TITLE
Repository for Ubuntu 15.10 missing?

### ISSUE THREAD

**Issue by skorokithakis** [tmate-io/tmate#65]
There doesn't seem to be a repository for Ubuntu Wily, the URL for it produces a 404. Would it be possible to add it?

**Comment by nightscape** [comment]
:+1:

**Comment by jniesen** [comment]
:+1:

**Comment by nviennot** [comment]
I'll get it done by end of day

**Comment by nviennot** [comment]
In the meantime, here's a statically compiled 64bits binary: https://github.com/tmate-io/tmate.io/raw/gh-pages/static/2.2.0/linux-64/tmate

**Comment by nviennot** [comment]
Repos are coming.

Static builds are now on the release page: https://github.com/tmate-io/tmate/releases

**Comment by skorokithakis** [comment]
Are there any news on this? Xenial is almost upon us and there's still no Wily repo, even though there are the packages.

**Comment by nviennot** [comment]
Oh yes, check on https://tmate.io the Ubuntu tab in the install section
