### ISSUE TITLE
tmate disconnects if base-index is 1 in .tmux.conf

### ISSUE THREAD

**Issue by jmoody** [tmate-io/tmate#66]
* MacOS Yosemite 10.10.5 and El Capitan 10.11.2
* installed with homebrew

This problem started when I returned from winter vacation on Monday Jan 4.

I narrowed down the problem to this line:

```
# Start tab numbering at 1
set -g base-index 1
```

* Gist of [.tmux.conf](https://gist.github.com/jmoody/ccd1d44085f829cc44e9)

If I remove that line, tmate works as expected.

I am not sure if this is helpful, but I have provided some shell output and the [log files as a gist](https://gist.github.com/jmoody/38e684203a26df1f8548).

```
$ tmate -V
tmate 1.8.10

$ tmate -v
# Shows 'Disconnected' in tmux pane

$ tmate show-message
Tue Jan  5 14:41:06 2016 [tmate] Connecting to master.tmate.io...
Tue Jan  5 14:41:07 2016 [tmate] Remote session read only: ssh ro-S<snip>Q@fk2.tmate.io (clear your screen if you share this)
Tue Jan  5 14:41:07 2016 [tmate] Remote session: ssh Z<snip>0@fk2.tmate.io
Tue Jan  5 14:41:07 2016 [tmate] Error reading from channel: Socket error: disconnected
Tue Jan  5 14:41:07 2016 [tmate] Disconnected

# In another shell
$ ssh Z<snip>0@fk2.tmate.io
Are you sure you want to continue connecting (yes/no)? yes
  
  Dear guest,
  
  The provided session token is invalid, or has expired.
  Feel free to reach out if you are having issues.
  
  Thanks,
  Nico
  
Connection to fk2.tmate.io closed by remote host.
Connection to fk2.tmate.io closed.
```

**Comment by nviennot** [comment]
I can't reproduce.
Try with `brew install tmate --HEAD` and let me know if the issue still happen.
Do you get a disconnection as soon as you connect?

**Comment by jmoody** [comment]
> Do you get a disconnection as soon as you connect?

Yes.  Immediately.

**Comment by jmoody** [comment]
```
$ brew install tmate --HEAD
Warning: nviennot/tmate/tmate-1.8.10 already installed
```

This might be of interest / related.  Connect clients cannot change panes:

```
c-b 1 => "Window not found:  :=1"
```

but this works normally in the host shell.

**Comment by nviennot** [comment]
Try to `brew update` before, or uninstalling tmate before installing the `--HEAD` version.

Can you send me a .tmux.conf that reproduces the bug if the issue still persists?

**Comment by jmoody** [comment]
> brew update + clean uninstall

I did this before I create the issue and again just now.

I can reproduce with a .tmux.conf with one line:

```
set -g base-index 1
```

**Comment by jmoody** [comment]
I can reproduce in Terminal.app or iTerm.  I am using bash.

**Comment by jmoody** [comment]
tmux itself works with base-index 1.

**Comment by nviennot** [comment]
I can reproduce!

**Comment by jmoody** [comment]
Whew!  I thought I was going mad.

**Comment by jmoody** [comment]
Fix works for me.  Thank you very much.

**Comment by fripSide** [comment]
The package in ubuntu seems not fix this bug. And I can't use many tmux default key-bindings, such as C-b x, C-b :, C-b w.
