### ISSUE TITLE
tmate msgpack >= 1.1.0 not found

### ISSUE THREAD

**Issue by peterzhao** [tmate-io/tmate#68]
I try to install tmate on centos6.5 but get error: tmate msgpack >= 1.1.0 not found

git clone https://github.com/tmate-io/tmate.git
cd tmate
./autogen.sh
./configure
make
make install

I followed https://github.com/msgpack/msgpack-c and installed msgpack 1.3 and try to install tmate again but got the same error.

**Comment by peterzhao** [comment]
my installation code worked about 20 days ago. I found this issue when I destroyed my VM today and tried to provision a new VM using the above code.

**Comment by emepetres** [comment]
Same problem here; I'm using Debian Jessie and I have installed  "libmsgpack-dev" "libmsgpack3" "libmsgpackc2" "ruby-msgpack"

I tried commentating the MSGPACK check section in "configure.ac".

"configure" executes correctly, but then make fails with this result:
tmate-msgpack.c: In function ‘msgpack_pack_string’:
tmate-msgpack.c:36:2: warning: implicit declaration of function ‘msgpack_pack_str’ [-Wimplicit-function-declaration]
  msgpack_pack_str(pk, len);
  ^
tmate-msgpack.c:36:2: warning: nested extern declaration of ‘msgpack_pack_str’ [-Wnested-externs]
tmate-msgpack.c:37:2: warning: implicit declaration of function ‘msgpack_pack_str_body’ [-Wimplicit-function-declaration]
  msgpack_pack_str_body(pk, str, len);
  ^
tmate-msgpack.c:37:2: warning: nested extern declaration of ‘msgpack_pack_str_body’ [-Wnested-externs]
tmate-msgpack.c: In function ‘unpack_buffer’:
tmate-msgpack.c:135:26: error: ‘MSGPACK_OBJECT_STR’ undeclared (first use in this function)
  if (uk->argv[0].type != MSGPACK_OBJECT_STR &&
                          ^
tmate-msgpack.c:135:26: note: each undeclared identifier is reported only once for each function it appears in
tmate-msgpack.c:136:26: error: ‘MSGPACK_OBJECT_BIN’ undeclared (first use in this function)
      uk->argv[0].type != MSGPACK_OBJECT_BIN)
                          ^
tmate-msgpack.c:139:24: error: ‘msgpack_object_union’ has no member named ‘str’
  *len = uk->argv[0].via.str.size;
                        ^
tmate-msgpack.c:140:24: error: ‘msgpack_object_union’ has no member named ‘str’
  *buf = uk->argv[0].via.str.ptr;
                        ^
Makefile:860: recipe for target 'tmate-msgpack.o' failed

**Comment by nviennot** [comment]
if you install msgpack from https://github.com/msgpack/msgpack-c you might have to use ./configure --prefix=/usr as opposed to /usr/local. I'm not sure. I don't have enough bandwidth to provide .debs and all for msgpack :(

**Comment by nviennot** [comment]
Maybe I should provide a statically linked compiled version of tmate that runs on any linux kernel.

**Comment by peterzhao** [comment]
I tried using "use ./configure --prefix=/usr" to install msgpack but got the same result. I think the statically linked compiled version of tmate would be very useful. Looking forward to seeing it.

**Comment by nviennot** [comment]
Here's a statically linked 64bits linux binary:

https://github.com/tmate-io/tmate.io/raw/gh-pages/static/2.2.0/linux-64/tmate

let me know if that works for you

**Comment by nviennot** [comment]
Pushed the static builds at: https://github.com/tmate-io/tmate/releases

**Comment by peterzhao** [comment]
I got the following error when run the static binary: 

        [root@dashboard-server tmate-2.2.0-static-linux64]# ./tmate 
        ./tmate: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./tmate)
        ./tmate: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./tmate)
       ./tmate: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./tmate)

Should I install some dependencies?  Or did I do something wrong? Thanks

**Comment by nviennot** [comment]
you are running https://github.com/tmate-io/tmate.io/raw/gh-pages/static/2.2.0/linux-64/tmate or the ones at https://github.com/tmate-io/tmate/releases ?

**Comment by nviennot** [comment]
from your copy/paste, I can see that it's the latter. I made a mistake to build on a too recent version of libc.

The former statically links libc, but this can be problematic on certain systems and produce segfaults.

**Comment by nviennot** [comment]
I've updated the binaries on https://github.com/tmate-io/tmate/releases -- you should be good to go on centos 6.5

**Comment by peterzhao** [comment]
This one works. Thanks so much!

**Comment by emepetres** [comment]
It works perfectly! Thank you, great app!
