### ISSUE TITLE
configure: error: "msgpack >= 1.1.0 not found"

### ISSUE THREAD

**Issue by intfrr** [tmate-io/tmate#70]
On centos i have the following error

```
configure: error: "msgpack >= 1.1.0 not found"
```

I installed msgpack-devel and python-msgpack and it does not work

**Comment by nviennot** [comment]
you probably installed an old version of msgpack then.

**Comment by intfrr** [comment]
I use centos 7, just dis ```yum install msgpack.```

**Comment by nviennot** [comment]
You can use the static builds: https://github.com/tmate-io/tmate/releases/tag/2.2.0
or you can install a newer version of msgpack

**Comment by intfrr** [comment]
I'm sorry, what package do I have to install on centos 7?

**Comment by nviennot** [comment]
I don't know

**Comment by hh** [comment]
I found this issue while trying to build in an embedded environment:
I started with  https://github.com/msgpack/msgpack-c#install-from-git-repository
and after ```make install``` I had:

```
root@iikeyboard:/usr/local# ls include/msgpack.* 
include/msgpack.h  include/msgpack.hpp
root@iikeyboard:/usr/local# ls -la ./lib/libmsgpackc.*
-rw-r--r-- 1 root staff 94126 Feb 24 19:09 ./lib/libmsgpackc.a
-rwxr-xr-x 1 root staff   963 Feb 24 19:09 ./lib/libmsgpackc.la
lrwxrwxrwx 1 root staff    20 Feb 24 19:09 ./lib/libmsgpackc.so -> libmsgpackc.so.2.0.0
lrwxrwxrwx 1 root staff    20 Feb 24 19:09 ./lib/libmsgpackc.so.2 -> libmsgpackc.so.2.0.0
-rwxr-xr-x 1 root staff 71680 Feb 24 19:09 ./lib/libmsgpackc.so.2.0.0
root@iikeyboard:/usr/local# ls include/msgpack.*
include/msgpack.h  include/msgpack.hpp
```

**Comment by Juraci** [comment]
Same problem happening on Debian Jessie 8.8.

on the `./configure` step I'm having the error `configure: error: "msgpack >= 1.1.0 not found"`

No package available in the apt repository seems to fulfill this requirement.
I installed the following:

```@bash
libmsgpack-dev - binary-based efficient object serialization library
libmsgpack3 - binary-based efficient object serialization library
libmsgpackc2 - binary-based efficient object serialization library
```
no success

**Comment by JohnGarbutt** [comment]
FWIW I needed this on CentOS 7:
yum install msgpack-devel

**Comment by imdreamrunner** [comment]
@Juraci did you managed to solve the issue? I am using Debian and have the same error.

**Comment by Juraci** [comment]
@imdreamrunner No I did not. I ended up giving up on tmate and using SSH + tmux to pair remotely.

**Comment by crashcoredump** [comment]
I know this is closed but I just had to work through this myself on Raspbian:

```
apt-get install cmake
git clone https://github.com/msgpack/msgpack-c.git 
cd msgpack-c
cmake .
make
make install
```

Then proceed with building tmate as instructed by the author.

**Comment by ssbarnea** [comment]
Even after compiling and installing msg pack tmate fails to run .configure with the same error.
