### ISSUE TITLE
error connecting to /private/tmp/... (No such file or directory)

### ISSUE THREAD

**Issue by aristidesfl** [tmate-io/tmate#72]
```
$ tmate

$ tmate show-messages
error connecting to /private/tmp/tmate-501/XzdBjp (No such file or directory)
```
```
$ ls /private/
drwxrwxrwt   8 root wheel  272 Feb 18 20:18 tmp/

$ ls /private/tmp
total 8.0K
drwx------ 3 user wheel  102 Feb 17 22:44 com.apple.launchd.ggB4kKpNv1/
drwx------ 3 user wheel  102 Feb 17 22:44 com.apple.launchd.JoPaHslAPh/
-rw-rw-rw- 1 user wheel    0 Feb 17 22:44 .keystone_install_lock
-rw-r--r-- 1 user wheel 4.3K Feb 17 22:47 wbxtra_02172016_224658.wbt
drwx------ 3 user wheel  102 Feb 18 19:25 'KSOutOfProcessFetcher.501.sAglCyxY5lzPoNgfmEvv-ZqGl-w='/
drwx------ 4 user wheel  136 Feb 18 20:20 tmate-501/

$ ll /private/tmp/tmate-501/
total 0
srw-rw---- 1 user wheel 0 Feb 18 20:18 LZGbIe=
srw-rw---- 1 user wheel 0 Feb 18 20:20 WX74Pv=
srw-rw---- 1 user wheel 0 Feb 18 20:30 d4gdnb=
```

OSX 10.11.3

**Comment by nviennot** [comment]
Hum... I can't reproduce the issue :(

**Comment by aristidesfl** [comment]
The problem seems to be that the name of the folder being created differs from the name tmate is trying to access.

**Comment by nviennot** [comment]
Are you running the `tmate show-messages` command within the tmate session?

**Comment by aristidesfl** [comment]
I believe so, I run `tmate`, my terminal gets cleared, and then I do the `tmate show-message`. Other than that my termianl looks normal, there is no indication that it is tmate

**Comment by nviennot** [comment]
I'm not sure what's going on :(

**Comment by aristidesfl** [comment]
I don't get the tmux bar on the bottom when I run tmate, so maybe its not working. Do I need to have tmux installed?

**Comment by nviennot** [comment]
that's suspicious. Run tmate with "-vvv", which will generate two log files (tmate-*.log). Let's see them

**Comment by aristidesfl** [comment]
https://gist.github.com/aristidesfl/89f5ef282c443932bf7c

**Comment by nviennot** [comment]
everything seems to be fine, even the ssh connection strings are showing up

**Comment by aristidesfl** [comment]
but I should be seeing a bar on the bottom no?

**Comment by nviennot** [comment]
yes, I'm not sure how to debug this issue

**Comment by aristidesfl** [comment]
maybe `tmate` is executing and exiting immediately. my login shell is set to `fish`, could that be the problem?

**Comment by nviennot** [comment]
try:

1) running `tmate new-session bash`
2) remove any ~/.tmux.conf that may be doing something funny

**Comment by aristidesfl** [comment]
It was ~/.tmux.conf
```
set -g mode-mouse on
set -g mouse-resize-pane on
set -g mouse-select-pane on
set -g mouse-select-window on

new-session
```

Specifically the new-session statement. 
The other options give this:
```
/Users/user/.tmux.conf:1: unknown option: mode-mouse                                                                                                                                                  
/Users/user/.tmux.conf:2: unknown option: mouse-resize-pane
/Users/user/.tmux.conf:3: unknown option: mouse-select-pane
/Users/user/.tmux.conf:4: unknown option: mouse-select-window
```
Any idea why? Admittedly I've not used tmux for a long time.

**Comment by nviennot** [comment]
Cool :)

Top entry of https://raw.githubusercontent.com/tmux/tmux/master/CHANGES explains it

**Comment by aristidesfl** [comment]
Thanks!
