### ISSUE TITLE
Ability to squelch startup message spam

### ISSUE THREAD

**Issue by mcmillion** [tmate-io/tmate#74]
Is there a way to silence the startup spam telling me about the html5 version and upgrade information? Currently I can't see the status bar for ~30 seconds when I start tmate.

**Comment by nviennot** [comment]
1) I can take out the html5 message.
2) For the upgrade information, are you running an older version?

**Comment by mcmillion** [comment]
I am currently and it's for compatibility reasons with some older stuff. I've been pushing people to upgrade, but something in our VM setup breaks pairing when we do. Pretty sure its not in tmate though, it's local config stuff.

**Comment by nviennot** [comment]
I'm not going to push new stuff in production just yet. Meanwhile, you can put `set -g tmate-display-time 1000` in your config file to have tmate messages displayed only one second.

**Comment by mcmillion** [comment]
That'll work beautifully. Thanks!
