### ISSUE TITLE
Issue during detach/reattach

### ISSUE THREAD

**Issue by felixhammerl** [tmate-io/tmate#76]
Hi,

i was detached in a weird way from my running tmate session after sleep/wakeup. The session detached in a seemingly dirty state and I can't seem to recover it. I was using the iterm integration on Mac OS via `tmate -CC`.

I can't seem to list the open sessions:

```
> tmate ls
error connecting to /private/tmp/tmate-501/JYblyp (No such file or directory)
> tmate show-messages
error connecting to /private/tmp/tmate-501/mOMLb8 (No such file or directory)
```

Even though it seems there are quite a number of things that need cleanup...

```
> ls /private/tmp/tmate-501/
total 0
srw-rw----  1 eufhammerl  wheel     0B Mar 10 09:38 2YQqDa=
srw-rw----  1 eufhammerl  wheel     0B Mar 16 10:57 5vozhl=
srw-rw----  1 eufhammerl  wheel     0B Mar 10 17:59 EoYGNU=
srw-rw----  1 eufhammerl  wheel     0B Mar 10 23:39 HYqxPp=
srw-rw----  1 eufhammerl  wheel     0B Mar 10 23:19 PA5K26=
srw-rw----  1 eufhammerl  wheel     0B Mar 10 09:41 SO0yh9=
srw-rw----  1 eufhammerl  wheel     0B Mar 10 09:42 Zag9bP=
srw-rw----  1 eufhammerl  wheel     0B Mar 11 00:04 b5h15U=
srwxrwx---  1 eufhammerl  wheel     0B Mar 15 17:37 jrFdTW=
srw-rw----  1 eufhammerl  wheel     0B Mar 16 10:54 tv4Zce=
srw-rw----  1 eufhammerl  wheel     0B Mar 11 00:17 uGPpAR=
srw-rw----  1 eufhammerl  wheel     0B Mar 10 09:36 zplbes=
```

Using:
iTerm: Build 2.9.20160206
MacOS: 10.11.3 (15D21)
tmate: 2.2.0

I can open new session, I just can't do anything about the "lost" session... If this is totally irrelevant, feel free to discard this.

**Comment by nviennot** [comment]
You have to fixate the tmate session with `-S /tmp/tmate.sock` for example. Otherwise it will do all this.
I'll make sure to improve the error messages on the next release :)

**Comment by felixhammerl** [comment]
for future reference:
so `$ tmate ls` does not really make sense unless it's run with a specific socket via ` tmate -S /tmp/my-socket ls`

`$ tmate ls` always displays the error message with a random socket not being available, which actually makes sense when it is told to use ephemeral random sockets :) see below...

```
> ls /private/tmp/tmate-501/
total 0
srwxrwx---  1 eufhammerl  wheel     0B Mar 17 10:27 gSwhTz=
> tmate -S /private/tmp/tmate-501/gSwhTz ls
0: 1 windows (created Thu Mar 17 10:27:22 2016) [80x24] (attached)

(... tmate session closed ...)
> tmate -S /private/tmp/tmate-501/gSwhTz ls
no server running on /private/tmp/tmate-501/gSwhTz
```

Thanks for helping me understand this :)

Is there a reason why the ephemeral sockets don't get cleaned up, when they're not reused anyway? They don't really get in the way, it's just that they're still there...

**Comment by nviennot** [comment]
No reason. It would be nicer if they would get cleaned up indeed.
