### ISSUE TITLE
read only session issue

### ISSUE THREAD

**Issue by mpetrive** [tmate-io/tmate#77]
I setup my own server with tmate-slave on a RH6 machine.  I am able to connect from an Ubu 14 client (client1),  create a new session and obtain a ready only ssh connection (tmate show-messages).  I then use the ro ssh connection string on another Ubu 14 machine (client2).  Everything looks great and I can monitor the session.  However, inside the read-only session (client2), I issue an SSH disconnect command ([enter]~.) which terminates the SSH connection, i see a "connection to client2 closed" however the tmate client remains open.  Not only does it remain open but it leaves me with a full access ssh connection to client1.  I'm not a SSH/tunneling/tmux/screen expert by any means, but this doesn't sound right.  Basically I am going from a read only ssh session to the tmate-slave server to completely new, and full access, ssh session on the session originator.  Is this a bug or am I just misunderstanding the way this works?

**Comment by nviennot** [comment]
> ), I issue an SSH disconnect command ([enter]~.) which terminates the SSH connection, i see a "connection to client2 closed" however the tmate client remains open

It doesn't. It returns you back to your shell: the openssh client is closed. There's no way you can interact with the remote session at this point.
Maybe there is the illusion that it's working, because the ssh client doesn't clear the screen upon disconnection.

Please confirm the illusion.

**Comment by mpetrive** [comment]
The fact I had my filesystem mirrored onto a couple systems combined with the leftovers from the ssh session led me to believe I was on a different machine than I was.  Sorry for wasting your time an keep up the great work!!
