### ISSUE TITLE
[BUG] - homebrew-tmate not found - homebrew

### ISSUE THREAD

**Issue by marioidival** [tmate-io/tmate#80]
fatal: repository 'https://github.com/tmate-io/homebrew-tmate/' not found
Error: Fetching /usr/local/Library/Taps/tmate-io/homebrew-tmate failed!

**Comment by nviennot** [comment]
I removed it.
tmate is now in the official homebrew repository, so no need for such tap.

**Comment by slashmili** [comment]
FYI you need to remove `nviennot/tmate`, otherwise `brew update` fails with 

```
$ brew update
error: unable to read askpass response from 'false'
fatal: could not read Username for 'https://github.com': terminal prompts disabled
Error: Fetching /usr/local/Library/Taps/nviennot/homebrew-tmate failed!
```

to remove the tap

```
$ brew untap nviennot/tmate
Untapping nviennot/tmate... (35 files, 24.5K)
Untapped 1 formula``

**Comment by teamcityreporting** [comment]
Running into this myself

**Comment by nviennot** [comment]
try `brew untap tmate-io/tmate`
