### ISSUE TITLE
Backspace no longer works 

### ISSUE THREAD

**Issue by joelash** [tmate-io/tmate#81]
I'm running `2.2.0`. Within the past few weeks I've noticed that anyone connected to the session cannot send a backspace command, it seems to be escaped improperly. (`<F9>` comes across in vim and `0~` in bash prompt). Running an `od -x` and typing `backspace`, `enter`, `Ctrl-c` I see:

```
$ od -x
^[[20~
0000000      5b1b    3032    0a7e
0000006
```

**Comment by nviennot** [comment]
Hum.... I can't reproduce neither on my linux box, or macos.
Can you help me reproduce this problem?
Maybe you can give me a tmate access to your box so I can investigate the issue? (if you do so, send connection string via email)

**Comment by joelash** [comment]
Would love too, but can we find a time that I can be on too? Maybe do a Skype call or something so you can see the issue?


Thanks,
Joel

**Comment by nviennot** [comment]
Cool!
Give me two different timeslots that works for you, and I'll pick one

**Comment by joelash** [comment]
I'm in the central timezone, and anytime Monday between 8a-5p or Tuesday 8a-3:30p works for me.

**Comment by nviennot** [comment]
cool! let's do 2pm today?
Send me a tmate connection string via email, and we'll go from here

**Comment by nviennot** [comment]
All the servers are running with the patch now, please confirm it's working for you (ps: you'll have to take out the stuff we put in ~/.tmate.conf so it doesn't connect to your local server)

**Comment by joelash** [comment]
It's working now. Thanks!

**Comment by nviennot** [comment]
awesome! enjoy
have a good one
