### ISSUE TITLE
Client: Error reading from channel: Socket error: disconnected /  Server: [tmate] FATAL Received a bad message

### ISSUE THREAD

**Issue by snadal** [tmate-io/tmate#82]
Hello,

I'm setting up an internal tmate-slave server, but when running tmate, I got this message on the client

`Error reading from channel: Socket error: disconnected`

And this one on the server

`[tmate] FATAL Received a bad message`

I am attaching both server and client logs

[tmate-client-3649.txt](https://github.com/tmate-io/tmate/files/244658/tmate-client-3649.txt)
[tmate-server-3651.txt](https://github.com/tmate-io/tmate/files/244659/tmate-server-3651.txt)

Any hints ?

FYI, I tried using PPA build on Ubuntu 14.04 and 15.10 and tmate-slave is running on docker, built from sources. I could not build client from source as I needed to install latest msgpack, I'm not sure it this will help.

Thank you !

**Comment by nviennot** [comment]
make sure you are running the latest tmate-slave server version from the git repo, and you should be good

**Comment by snadal** [comment]
It seems I am alreadyn running 2.2.1 

On 14.04

`#  dpkg -s tmate`
> Package: tmate
> Status: install ok installed
> Priority: optional
> Section: admin
> Installed-Size: 701
> Maintainer: Nicolas Viennot <nicolas@viennot.biz>
> Architecture: amd64
> Version: 2.2.1-0~3~ubuntu14.04.1
> Depends: libc6 (>= 2.14), libevent-2.0-5 (>= 2.0.10-stable), libmsgpack3 (>= 0.5.1), libssh-4 (>= 0.6.1), libtinfo5, libutempter0 (>= 1.1.5)
> Conflicts: tmate-nightly
> Description: Fork of tmux, provides an instant pairing solution
>  tmate is a fork of tmux. tmate and tmux can coexist on the same system, they
>  do not conflict with each other.
> Homepage: http://tmate.io/

And on 15.10

`# dpkg -s tmate`

> Package: tmate
> Status: install ok installed
> Priority: optional
> Section: admin
> Installed-Size: 681
> Maintainer: Nicolas Viennot <nicolas@viennot.biz>
> Architecture: amd64
> Version: 2.2.1-0~3~ubuntu15.10.1
> Depends: libc6 (>= 2.14), libevent-2.0-5 (>= 2.0.10-stable), libmsgpack3 (>= 0.5.1), libssh-4 (>= 0.6.1), libtinfo5, libutempter0 (>= 1.1.5)
> Conflicts: tmate-nightly
> Description: Fork of tmux, provides an instant pairing solution
>  tmate is a fork of tmux. tmate and tmux can coexist on the same system, they
>  do not conflict with each other.
> Homepage: http://tmate.io/



I tried tmate-nightly without success. (same  


> Package: tmate-nightly
> Status: install ok installed
> Priority: optional
> Section: admin
> Installed-Size: 701
> Maintainer: Nicolas Viennot <nicolas@viennot.biz>
> Architecture: amd64
> Version: 2.2.1+201604212302+git3168~ubuntu14.04.1
> Depends: libc6 (>= 2.14), libevent-2.0-5 (>= 2.0.10-stable), libmsgpack3 (>= 0.5.1), libssh-4 (>= 0.6.1), libtinfo5, libutempter0 (>= 1.1.5)
> Conflicts: tmate
> Description: Fork of tmux, provides an instant pairing solution
>  tmate is a fork of tmux. tmate and tmux can coexist on the same system, they
>  do not conflict with each other.
> Homepage: http://tmate.io/

Do you think building from source will fix it ?

**Comment by nviennot** [comment]
I was referring to the internal tmate-slave server you are running, not the tmate binary

**Comment by snadal** [comment]
Ops, you're right :)

On Ubuntu 15.10 after compiling msgpack from source and install libssh 0.7 (ppa:kedazo/libssh-0.7.x),  everything ran fine.

Thank you !

**Comment by nviennot** [comment]
awesome!
