### ISSUE TITLE
Compiling tmate using musl libc

### ISSUE THREAD

**Issue by iperdomo** [tmate-io/tmate#83]
I was trying to use the tmate (client) static binary in an [Alpine Linux](http://gliderlabs.viewdocs.io/docker-alpine/) based  Docker container. My attempt failed (I guess because it was compiled using glibc).

I downloaded the code compiled `libssh` and `msgpack` following the provisioning scripts in [tmate-kichen](https://github.com/tmate-io/tmate-kitchen/tree/master/site-cookbooks/tmate_slave/recipes) and then patched the tmate code following this hints in [tmate-debug.c](https://github.com/goller/tmate-slave/commit/b347f11500adac4229006831bfd380c93da0950b)

After doing this I was able to use tmate from the container without any issue.

Could it be possible to support tmate compilation using musl without manually patching the code?

Many thanks for this great project.

**Comment by nviennot** [comment]
Sure!
However, you are patching a really old version of tmate-slave, so if you
show me a patch from master, I'd be able to do something with it.
Nico

**Comment by iperdomo** [comment]
Hi @nviennot 

This is a patch directly from `master` branch, the last commit in my local repo is fe81322cc

* https://gist.github.com/iperdomo/a74bab4397df36771e76f69f25200283

On the missing `execinfo.h`, someone suggests `libbacktrace`

* http://www.openwall.com/lists/musl/2015/04/09/3

The original requester ended up using http://www.nongnu.org/libunwind/

**Comment by iperdomo** [comment]
Fixed in changes related to #117 #116
