### ISSUE TITLE
[feature request] start tmate with Telegram bot and get ssh address in email.

### ISSUE THREAD

**Issue by SJ50** [tmate-io/tmate#85]
Is there anyway I can start tmate with Telegram bot and get ssh address in replay or in email?
edit- link to SSH address.

**Comment by nviennot** [comment]
that's a good question. at the moment no, but that shouldn't be too hard to implement with [https://github.com/tmate-io/tmate/wiki/Webhooks](webhooks)

**Comment by frriction** [comment]
I found dirty implementation of this request.
I am noob so can not change much below, hope this helps you to fulfill this request more securely and elegantly.


first install python telegram bot api
`sudo pip install pyTelegramBotAPI`
than get this file
`wget https://raw.githubusercontent.com/i32ropie/Telgram-Bots/master/ssh.py`
add token and admin id from telegram to above file.
There 4 indentation error on above file from line 21-24 just add 2 space before text.
run above script with python2.
Now you can execute any shell command and get output using telegram bot.
so run this two command to get tmate ssh address
`tmate -S /tmp/tmate.sock new-session -d`
`tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}`
above two command in one line 
`tmate -S /tmp/tmate.sock new-session -d && sleep 5 && tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'`

**Comment by nviennot** [comment]
Instead of sleeping, use `tmate -S /tmp/tmate.sock wait tmate-ready`

**Comment by fredericofs** [comment]
I found sometimes the command:
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}
will output a session that is already closed by the server (impossible to connect form outside).
When it should report a blank output, or dead session.
