### ISSUE TITLE
Is there a way to get the ssh session url from the command line?

### ISSUE THREAD

**Issue by squanto** [tmate-io/tmate#86]
I'm working on a chat roulette for pair programming, and trying to automatically start and share a tmate session. How would you go about getting the ssh session url from the command line? I see the following in the tmate server log

`
1463519270.654744 [tmate] D ssh session read only: ssh foobarbaz@ny2.tmate.io
1463519270.654763 [tmate] D ssh session: ssh foobarbaz1@ny2.tmate.io
`

But I'm not sure that's the best way to go about it

**Comment by nviennot** [comment]
```
tmate -S /tmp/tmate.sock new-session -d               # Launch tmate in a detached state
tmate -S /tmp/tmate.sock wait tmate-ready             # Blocks until the SSH connection is established
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'    # Prints the SSH connection string
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh_ro}' # Prints the read-only SSH connection string
tmate -S /tmp/tmate.sock display -p '#{tmate_web}'    # Prints the web connection string
tmate -S /tmp/tmate.sock display -p '#{tmate_web_ro}' # Prints the read-only web connection string
```
