### ISSUE TITLE
compile static builds with -static-libgcc

### ISSUE THREAD

**Issue by hh** [tmate-io/tmate#88]
https://github.com/tmate-io/tmate/releases has some tarballs listed at 'static binaries' but they are shared (at least for GLIBC)

And on cento5 boxes results in inability to run:

```
# tmate
tmate: /lib64/libc.so.6: version `GLIBC_2.8' not found (required by tmate)
tmate: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by tmate)
```

```
# ldd ./tmate-2.2.1-static-linux-i386/tmate 
./tmate-2.2.1-static-linux-i386/tmate: /lib/libc.so.6: version `GLIBC_2.8' not found (required by ./tmate-2.2.1-static-linux-i386/tmate)
./tmate-2.2.1-static-linux-i386/tmate: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./tmate-2.2.1-static-linux-i386/tmate)
        linux-gate.so.1 =>  (0xffffe000)
        libdl.so.2 => /lib/libdl.so.2 (0x00834000)
        libc.so.6 => /lib/libc.so.6 (0x006ba000)
        /lib/ld-linux.so.2 (0x0069b000)
```

I've tried building with an older GLIBC, but still failing due to trying to update tall the other libs.
Can we statically compile and include the C runtime in the binary?

**Comment by hh** [comment]
```
# file /lib64/libc-2.5.so 
/lib64/libc-2.5.so: ELF 64-bit LSB shared object, AMD x86-64, version 1 (SYSV), for GNU/Linux 2.6.9, not stripped
```

**Comment by hh** [comment]
```
# file /usr/local/bin/tmate 
/usr/local/bin/tmate: ELF 64-bit LSB executable, AMD x86-64, version 1 (SYSV), for GNU/Linux 2.6.24, dynamically linked (uses shared libs), stripped
```

**Comment by hh** [comment]
```
# file ./tmate-2.2.1-static-linux-i386/tmate 
./tmate-2.2.1-static-linux-i386/tmate: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), for GNU/Linux 2.6.24, dynamically linked (uses shared libs), stripped
```

**Comment by nviennot** [comment]
The libc dependency is pretty hard to remove due to networking (e.g. resolving a host name may go through a bunch things in /etc, and may invoke some custom .so to do so).
If you have a solution, I'll take it :)

**Comment by hh** [comment]
if we compile against an old GLIBC so we don't use any of the newer calls :) should be forward compatible and work on these old boxes.

Is there a way I can work on a branch (or PR) and have the commits flow through your build system without bothering you?

**Comment by nviennot** [comment]
What I use to do is to use `make -f Makefile.static-build` and look at the symbols with objdump and make sure I didn't have anything above GLIBC_2.8. That required me to implement some of the calls. See commit https://github.com/tmate-io/tmate/commit/6dc58ab6deef30020953882331c88ca6c80b4f2d for the trick used with memcpy() for example.
So locate the calls that use a newer glibc, and add a wrapper around them.
You can make PR without upsetting my build system (because I don't really have build system in place).

**Comment by nviennot** [comment]
I fixed that. Now the releases are really static.
