### ISSUE TITLE
-vv log for trying to run tmate with powerline in the tmux config.

### ISSUE THREAD

**Issue by dpnova** [tmate-io/tmate#89]
12049 1465871031.354433 loading /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf
12050 1465871031.354451 /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf: set -g status on
12051 1465871031.354461 /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf: set -g status-utf8 on
12052 1465871031.354468 /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf: set -g status-interval 2
12053 1465871031.354475 /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf: set -g status-left-length 20
12054 1465871031.354487 /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf: set -g status-right '#(eval $POWERLINE_COMMAND tmux right -R pane_id=`tmux display -p "#D"`)'
12055 1465871031.354497 /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf: set -g status-right-length 150
12056 1465871031.354507 /usr/lib64/python2.7/site-packages/powerline/bindings/tmux/powerline-base.conf: set -g window-status-format "#[$_POWERLINE_WINDOW_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER_SPACES#I #[$_POWERLINE_WINDOW_DIVIDER_COLOR]$_POWERLINE_LEFT_SOFT_DIVIDER#[default]#W $_POWERLINE_LEFT_HARD_DIVIDER_SPACES"
12057 1465871031.354517 [tmate] I CRASH, printing stack trace
12058 1465871031.354958 [tmate] I ============ 20 stack frames ============
12059 1465871031.354964 [tmate] I tmate() [0x44c785]
12060 1465871031.354967 [tmate] I /lib64/libc.so.6(+0x33160) [0x7fd010280160]
12061 1465871031.354970 [tmate] I /lib64/libc.so.6(strlen+0x26) [0x7fd0102cb526]
12062 1465871031.354973 [tmate] I /lib64/libc.so.6(__strdup+0xe) [0x7fd0102cb24e]
12063 1465871031.354976 [tmate] I tmate(xstrdup+0x9) [0x4614d9]
12064 1465871031.354978 [tmate] I tmate(cmd_string_variable+0x136) [0x427bb6]
12065 1465871031.354981 [tmate] I tmate(cmd_string_string+0x174) [0x427e74]
12066 1465871031.354984 [tmate] I tmate(cmd_string_parse+0x2f4) [0x4283f4]
12067 1465871031.354986 [tmate] I tmate(load_cfg+0xee) [0x419ace]
12068 1465871031.354989 [tmate] I tmate(cmd_source_file_exec+0x4f) [0x4272ef]
12069 1465871031.354992 [tmate] I tmate(cmdq_continue+0xd3) [0x423473]
12070 1465871031.354994 [tmate] I tmate(server_client_dispatch_command+0xaa) [0x4445ca]
12071 1465871031.354997 [tmate] I tmate(server_client_dispatch+0x177) [0x444c47]
12072 1465871031.355000 [tmate] I tmate() [0x43ee00]
12073 1465871031.355003 [tmate] I /usr/lib64/libevent-2.1.so.5(+0x203a4) [0x7fd010a1f3a4]
12074 1465871031.355006 [tmate] I /usr/lib64/libevent-2.1.so.5(event_base_loop+0x56f) [0x7fd010a2013f]
12075 1465871031.355008 [tmate] I tmate(proc_loop+0x2f) [0x43f0df]
12076 1465871031.355011 [tmate] I tmate(server_start+0x18f) [0x4466bf]
12077 1465871031.355014 [tmate] I tmate(client_connect+0x1fc) [0x41a3fc]
12078 1465871031.355018 fatal: [tmate] CRASHED

**Comment by nviennot** [comment]
I can't reproduce the crash, but I tried to fix it based on the call stack.

Try this branch: https://github.com/tmate-io/tmate/tree/env-crash and tell me if that fixes the bug.

Thank you :)

**Comment by dpnova** [comment]
This definitely does handle the crash. I've included the new sever log for completeness. Feel free to close this issue once you've merged the feature branch.

[tm.zip](https://github.com/tmate-io/tmate/files/314762/tm.zip)

 :+1: Thanks!

For anyone else who comes looking at this for how to get powerline working in tmate, I recommend using this set of themes instead: https://github.com/jimeh/tmux-themepack
