### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by deatheragetr** [tmate-io/tmate#90]
Hello, 
From a computer on which I've previously been able to connect with tmate, I get the following:
```
$ tmate show-messages
Tue Jun 14 11:16:30 2016 [tmate] Reconnecting... (Error connecting: Connection refused)
Tue Jun 14 11:16:32 2016 [tmate] Connecting to 75.101.230.84...
Tue Jun 14 11:16:32 2016 [tmate] Error connecting: Connection refused
Tue Jun 14 11:16:32 2016 [tmate] Reconnecting... (Error connecting: Connection refused)
Tue Jun 14 11:16:34 2016 [tmate] Connecting to 75.101.230.84...
Tue Jun 14 11:16:34 2016 [tmate] Error connecting: Connection refused
```

Similarly,
```
$ ssh master.tmate.io
Invalid session token
Connection to master.tmate.io closed by remote host.
Connection to master.tmate.io closed.
```
I _do_ have ssh keys, although I vaguely remember having to change them at one point in the not too distant past, which I suppose may be affecting authentication.  If that is the case, I've no clue how to tell tmate to use my new public key.

Any ideas? 

Thanks

**Comment by nviennot** [comment]
Remove your `.tmate.conf` and try again

**Comment by deatheragetr** [comment]
Yep that did it -- thanks.  Didn't know I had that.

**Comment by nviennot** [comment]
cool
