### ISSUE TITLE
Always complain about "must specify socket name with -S"

### ISSUE THREAD

**Issue by spinwang** [tmate-io/tmate#92]
On mac El Captain 10.11.2

```
$ tmate -S /tmp/some.sock wait tmate-ready
You must specify a socket name with -S. For example:
  tmate -S /tmp/tmate.sock new-session -d
  tmate -S /tmp/tmate.sock wait tmate-ready
```

The above command does not work, even though I have already included the `-S`

```
tmate -S /tmp/some.sock
```

works. But I would like to get the ssh string back from the command directly.

**Comment by spinwang** [comment]
I realized that I need to run `tmate -S /tmp/tmate.sock new-session -d` first.

**Comment by nathantech2005** [comment]
I get 

    multi sessions is not supported with tmate

**Comment by ethervoid** [comment]
In my case, I didn't realize that I need to launch `tmate show-sessions` inside a tmate session instead of outside

**Comment by wfernandes** [comment]
I witnessed this issue on my mac recently. I was able to fix this by checking my `~/.tmux.conf`. I had some bad config in here that would make `tmate` print out the message above. I'll add more details here when I find the offending line in my `~/.tmux.conf`.

**Comment by megalithic** [comment]
@wfernandes any luck on finding the offending line(s) of your `.tmux.conf` that made the above tmate sessions to fail?
