### ISSUE TITLE
Allow fullscreen in the web interface

### ISSUE THREAD

**Issue by Yamakaky** [tmate-io/tmate#94]
Currently, the view of the shared session via the web interface is limited to a div. It would be cool to be able to switch to fullscreen.

**Comment by nviennot** [comment]
👍

**Comment by svenk** [comment]
Sorry, but what _web interface_ do you refer to? This is not related to [the website of tmate](https://github.com/tmate-io/tmate.io), isn't it?

**Comment by svenk** [comment]
Okay, forget about it -- I just found there is really a HTML5 client which allows URLs like https://tmate.io/t/k4bxdUE78LNAZOtKdoP0HbzfEY where `ssh k4bxdUE78LNAZOtKdoP0HbzfEY@fk2.tmate.io` is the associated ssh address. This information can be found when going to the `show-messages` dialog by typing `tmate show-messages` or in a running session, `CTRL`-`b`, then `:show-messages`. This is really amazing. And indeed, the session should be fullscreenable!
