### ISSUE TITLE
Tmate ssh key not found in termux

### ISSUE THREAD

**Issue by Asternitix** [tmate-io/tmate#95]
i'm having a problem where tmate can't find my ssh key and connect to the server. Any ideas?

**Comment by step21** [comment]
I think I have the same issue. More precisely:

- On the host, tmate starts successfully, using a newly generated key pair
- When connecting as a mate, ssh tries several ssh keys but obv none work and does not connect. As I understood, connecting as a mate should not require ssh keys.

@Asternitix In case your issues relates to starting tmate on the host - create the standard id_rsa keypair by just running ssh-keygen without any options.

**Comment by nviennot** [comment]
both the host and the connecting mates needs an ssh key actually.
To avoid the use of an ssh key for a mate, you may use the web interface

**Comment by step21** [comment]
Well, the client in principle has ssh keys, but obviously none that tmate.io know about?

**Comment by nviennot** [comment]
true, but the other way was to request a password, which wasn't great

**Comment by step21** [comment]
Umh, meaning? Do the mates need the same ssh key as the host? If not, how do I tell tmate.io about the mate's key? If yes, out of band key sharing is ... :-/

**Comment by nviennot** [comment]
they don't need the be the same, just need a key on both the host and the mate.

**Comment by step21** [comment]
Ah ok. I think my problem was that I did have id_rsa, but with a password and didn't enter the password as I thought there is no way tmate.io can verify this...? Sorry for the confusion, thanks for helping out.

**Comment by nviennot** [comment]
ohh I see (the password is requested by libssh to read the private key, which is not transmitted to tmate.io)

**Comment by step21** [comment]
Yeah, sorry also my bad. Probably would have worked if I had entered the password but wasn't even sure anymore (my ssh keys are a mess) - I should know that it is verified locally. :)

**Comment by nviennot** [comment]
no worries :

**Comment by auscompgeek** [comment]
It is possible to have an SSH server without authentication…

**Comment by nviennot** [comment]
It is possible, I should have known better to keep it simple.
