### ISSUE TITLE
session closed, but client thinks its valid

### ISSUE THREAD

**Issue by nagualcode** [tmate-io/tmate#96]
I leave my home server with an open tmate session, to remote access it from other places.
Sometimes the sessions died, but my script still get a valid session login form the command:
tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}' 

Even thought it is impossible to connect to it from the other side, because server responds it is closed...
So how can my home server detect a closed session?  So far my script can only treat a blank output from: tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'  as a not valid session (and create a new one).

**Comment by nviennot** [comment]
The tmate client assumes it can eventually reconnect. In other words, the connection string should eventually be valid.

If that helps, you can use this api: `curl -L tmate.io/api/t/<session_token>` and watch the `closed_at` field. If it is not null, then the session is really closed (the client said it will not attempt to reconnect).

**Comment by nviennot** [comment]
Now you'll get a 404 if the session is really closed.
