### ISSUE TITLE
Arch Linux / Manjaro Packet

### ISSUE THREAD

**Issue by ds2k5** [tmate-io/tmate#99]
Hi,
may i help to build a Package for: Arch Linux / Manjaro Linux

PKGBULD

```
# Maintainer: ds2k5

pkgname=tmate-git
pkgver=2.2.1.r5.g608763a
pkgrel=1
pkgdesc="Tmate is a fork of tmux. It provides an instant pairing solution."
arch=("any")
url="https://github.com/tmate-io/tmate"
license=("BSD-licensed")
depends=('msgpack-c' 'openssh')
makedepends=('git')
conflicts=('tmate-git')
provides=('tmate-git')
options=(!emptydirs)
source=("${pkgname}::git+https://github.com/tmate-io/tmate")

md5sums=('SKIP')

prepare() {
	cd "${pkgname}"
}

pkgver() {
        cd "${pkgname}"
        git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g;s/^v//'
	}


build() {
	cd "${pkgname}"
	./autogen.sh
	./configure
	make
	strip tmate

}

package() {
	cd "${pkgname}"
	#mkdir -p "$pkgdir/usr/local/bin"
	#make INSTALL_ROOT="$pkgdir/${pkgname}" install
        make DESTDIR="$pkgdir/" install
}

```

Install with: makepkg && sudo pacman -U tmate-git-<Version>.pkg.tar.xz
for example: makepkg && sudo pacman -U tmate-git-2.2.1.r5.g608763a-1-any.pkg.tar.xz

then run: ssh-keygen

**Comment by nviennot** [comment]
thank you :)
I'm not sure where it should go. AUR?

**Comment by ds2k5** [comment]
>I'm not sure where it should go. AUR?

 

i see there is a package at AUR

so, i nice traning for me

 

 
 
 

Gesendet: Sonntag, 18. Dezember 2016 um 19:42 Uhr
Von: "Nicolas Viennot" <notifications@github.com>
An: tmate-io/tmate <tmate@noreply.github.com>
Cc: ds2k5 <dennisschneck@web.de>, Author <author@noreply.github.com>
Betreff: Re: [tmate-io/tmate] Arch Linux / Manjaro Packet (#99)


thank you :)
I'm not sure where it should go. AUR?

**Comment by eworm-de** [comment]
I pushed a package to the official repositories. So just run:
```
pacman -S tmate
```

**Comment by nviennot** [comment]
Thank you Christian
